import Link from 'next/link';
import Image from 'next/image';
import { Guide, guideBySlug, photoAssets, storeLinks } from './data';

export function Icon({ name }: { name: 'arrow' | 'camera' | 'shield' | 'check' | 'spark' | 'pin' }) {
  const paths: Record<string, string> = { arrow: 'M4 12h15m-6-6 6 6-6 6', camera: 'M4 7h3l1.5-2h7L17 7h3v11H4z M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z', shield: 'M12 3 20 6v5c0 5-3.4 8.3-8 10-4.6-1.7-8-5-8-10V6z M8.5 12l2.2 2.2 4.8-5', check: 'M5 12.5 9.2 17 19 7', spark: 'M12 2l1.7 7.3L21 11l-7.3 1.7L12 20l-1.7-7.3L3 11l7.3-1.7z', pin: 'M12 21s6-5.1 6-11a6 6 0 1 0-12 0c0 5.9 6 11 6 11z M12 12.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z' };
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
}

export function Header() { return <header className="site-header"><Link className="logo" href="/">NALVIUM<span>®</span></Link><nav className="desktop-nav"><Link href="/comment-ca-marche">Comment ça marche</Link><Link href="/guides">Guides</Link><Link href="/ma-maison">Ma maison</Link><Link href="/professionnels">Professionnels</Link></nav><Link className="header-cta" href="#diagnostic">Essayer NALVIUM <Icon name="arrow" /></Link><details className="mobile-menu"><summary aria-label="Ouvrir le menu">☰</summary><nav><Link href="/comment-ca-marche">Comment ça marche</Link><Link href="/guides">Guides</Link><Link href="/ma-maison">Ma maison</Link><Link href="/professionnels">Professionnels</Link></nav></details></header> }

export function Footer() { return <footer className="footer"><div><Link className="logo" href="/">NALVIUM<span>®</span></Link><p>Comprendre d’abord. Agir avec prudence.</p></div><div className="footer-links"><Link href="/securite">Sécurité</Link><Link href="/confidentialite">Confidentialité</Link><Link href="/cgu">CGU</Link><Link href="/communaute">Communauté</Link><Link href="/mentions-legales">Mentions légales</Link><a href="mailto:contact@nalvium.com">contact@nalvium.com</a></div><small>© {new Date().getFullYear()} NALVIUM. Gratuit pour les particuliers.</small></footer> }

export function ButtonLink({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) { return <Link className={secondary ? 'button button-secondary' : 'button'} href={href}>{children}{!secondary && <Icon name="arrow" />}</Link> }

export function AppDemo({ compact = false }: { compact?: boolean }) { return <div className={`demo-wrap ${compact ? 'demo-compact' : ''}`}><div className="demo-note note-top"><span className="live-dot" />Analyse en cours</div><div className="phone"><div className="phone-bar"><span>9:41</span><span className="phone-signal">•••　▰</span></div><div className="phone-appbar"><span className="app-mark">N</span><span>NALVIUM</span><span className="app-menu">•••</span></div><div className="leak-scene"><Image src={photoAssets.leakUnderSink.src} alt={photoAssets.leakUnderSink.alt} fill sizes="(max-width: 850px) 290px, 330px" quality={78} className="phone-photo" /></div><div className="analysis"><div className="analysis-status"><span className="status-check"><Icon name="check" /></span><span>J’analyse ce qui est visible…</span><b>82%</b></div><h3>L’eau apparaît près du raccord du siphon.</h3><p>Je ne peux pas encore confirmer la cause. Vérifions un point simple.</p><div className="question"><small>QUESTION 01 / 02</small><strong>La fuite apparaît-elle quand l’eau coule ?</strong><div className="answers"><button>Oui, seulement à ce moment</button><button>Non, elle coule en continu</button></div></div><div className="safe-line"><Icon name="shield" /> Une action à la fois, sans démontage.</div></div></div><div className="demo-note note-bottom"><span className="step-line" /><span>Observer <b>→</b> vérifier <b>→</b> décider</span></div></div> }

export function StoreBadges() { return <div className="store-badges" aria-label="Télécharger NALVIUM"><div className={`store-badge ${storeLinks.appStoreUrl ? '' : 'is-disabled'}`} aria-label={storeLinks.appStoreUrl ? 'Télécharger NALVIUM dans l’App Store' : 'Badge App Store à activer'}>{storeLinks.appStoreUrl ? <a href={storeLinks.appStoreUrl}><Image src="/images/stores/app-store-badge.svg" alt="Télécharger dans l’App Store" width={240} height={80} /></a> : <Image src="/images/stores/app-store-badge.svg" alt="App Store — lien à activer" width={240} height={80} />}</div><div className={`store-badge ${storeLinks.googlePlayUrl ? '' : 'is-disabled'}`} aria-label={storeLinks.googlePlayUrl ? 'Télécharger NALVIUM sur Google Play' : 'Badge Google Play à activer'}>{storeLinks.googlePlayUrl ? <a href={storeLinks.googlePlayUrl}><Image src="/images/stores/google-play-badge.svg" alt="Disponible sur Google Play" width={240} height={80} /></a> : <Image src="/images/stores/google-play-badge.svg" alt="Google Play — lien à activer" width={240} height={80} />}</div><span className="store-caption">Gratuit pour les particuliers</span></div> }

type CameraSceneProps = { compact?: boolean; showAction?: boolean; label?: string; priority?: boolean };
export function CameraScene({ compact = false, showAction = true, label = 'NALVIUM • CAMÉRA', priority = false }: CameraSceneProps) { return <div className={`camera-scene ${compact ? 'is-compact' : ''}`}><div className="scene-image"><Image src={photoAssets.leakUnderSink.src} alt={photoAssets.leakUnderSink.alt} fill sizes="(max-width: 850px) 100vw, 58vw" priority={priority} quality={82} className="scene-photo" /></div><div className="camera-top"><span><Icon name="camera" /> {label}</span><span>● LIVE</span></div><div className="focus-target"><i /><span>zone observée</span></div><div className="scene-observation"><small>CE QUE JE VOIS</small><strong>De l’eau apparaît près du raccord du siphon.</strong><p>Je vérifie avec vous avant de conclure.</p></div>{showAction && <div className="scene-action"><small>PROCHAINE ÉTAPE</small><strong>Fermez l’eau<br />avant de continuer.</strong><span><Icon name="arrow" /> une action à la fois</span></div>}</div> }

export function ObservationDemo() { return <section className="observation-demo"><div className="observation-heading"><span className="eyebrow">À TRAVERS NALVIUM</span><h2>NALVIUM ne donne pas une réponse magique.<br /><em>Il réduit l’incertitude, étape par étape.</em></h2></div><div className="observation-stage"><CameraScene showAction={false} /><div className="observation-panel"><div className="panel-label"><span>01</span> OBSERVATION <b>VISIBLE</b></div><h3>Présence d’eau au niveau du raccord inférieur.</h3><p>Pas encore un diagnostic.</p><div className="panel-question"><small>À VOUS</small><strong>La fuite apparaît-elle uniquement quand l’eau coule&nbsp;?</strong><div><button>Oui</button><button>Non</button><button>Je ne sais pas</button></div></div></div></div></section> }

export function ProblemGallery() { const items = [{ slug: 'fuite-sous-evier', title: 'Ça fuit sous l’évier', image: photoAssets.leakUnderSink, className: 'gallery-large' }, { slug: 'chasse-eau-qui-coule', title: 'La chasse d’eau coule', image: photoAssets.toilet, className: 'gallery-wide' }, { slug: 'lave-linge-ne-vidange-plus', title: 'Le lave-linge ne vidange plus', image: photoAssets.washingMachine, className: 'gallery-tall' }, { slug: 'evier-bouche', title: 'L’évier est bouché', image: photoAssets.cloggedSink, className: 'gallery-small' }].map(item => <Link key={item.slug} href={`/guides/${item.slug}`} className={`gallery-item ${item.className}`}><div className="gallery-photo"><Image src={item.image.src} alt={item.image.alt} fill sizes="(max-width: 430px) 100vw, (max-width: 850px) 50vw, 40vw" quality={78} className="gallery-photo-image" /><span className="gallery-focus" /></div><span>{item.title} <Icon name="arrow" /></span></Link>); return <div className="problem-gallery">{items}</div> }

export function Breadcrumbs({ items }: { items: { label: string; href?: string }[] }) { return <nav className="breadcrumbs" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link>{items.map((item) => <span key={item.label}>/ {item.href ? <Link href={item.href}>{item.label}</Link> : item.label}</span>)}</nav> }

export function GuideCard({ guide }: { guide: Guide }) { return <Link className="guide-card" href={`/guides/${guide.slug}`}><span className="card-kicker">{guide.category}</span><h3>{guide.title}</h3><p>{guide.quickAnswer}</p><span className="read-link">Lire le guide <Icon name="arrow" /></span></Link> }

export function SafetyStrip() { return <section className="safety-strip"><Icon name="shield" /><div><strong>La sécurité passe avant la réparation.</strong><p>Gaz, fumée, fils exposés, eau près d’une installation électrique ou fuite importante : NALVIUM arrête le guidage DIY et recommande une orientation adaptée.</p></div><Link href="/securite">Voir nos limites <Icon name="arrow" /></Link></section> }

export function FAQ({ items }: { items: { question: string; answer: string }[] }) { return <div className="faq">{items.map((item) => <details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</div> }

export function SiteCta({ title = 'Montrez le problème. NALVIUM vous guide.' }: { title?: string }) { return <section className="final-cta" id="diagnostic"><div><span className="eyebrow">GRATUIT POUR LES PARTICULIERS</span><h2>{title}</h2><p>Une photo suffit pour commencer. Vous gardez le contrôle à chaque étape.</p></div><ButtonLink href="/comment-ca-marche">Essayer NALVIUM</ButtonLink></section> }

export function RelatedGuides({ slugs }: { slugs: string[] }) { return <div className="related-grid">{slugs.map((slug) => guideBySlug[slug]).filter(Boolean).map((guide) => <GuideCard key={guide.slug} guide={guide} />)}</div> }
