import Link from 'next/link';
import Image from 'next/image';
import { Guide, guideBySlug, photoAssets, storeLinks } from './data';
import { MobileMenu } from './MobileMenu';

export function Icon({ name }: { name: 'arrow' | 'camera' | 'shield' | 'check' | 'spark' | 'pin' }) {
  const paths: Record<string, string> = { arrow: 'M4 12h15m-6-6 6 6-6 6', camera: 'M4 7h3l1.5-2h7L17 7h3v11H4z M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z', shield: 'M12 3 20 6v5c0 5-3.4 8.3-8 10-4.6-1.7-8-5-8-10V6z M8.5 12l2.2 2.2 4.8-5', check: 'M5 12.5 9.2 17 19 7', spark: 'M12 2l1.7 7.3L21 11l-7.3 1.7L12 20l-1.7-7.3L3 11l7.3-1.7z', pin: 'M12 21s6-5.1 6-11a6 6 0 1 0-12 0c0 5.9 6 11 6 11z M12 12.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z' };
  return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
}

export function Header() { return <header className="site-header"><Link className="logo" href="/" aria-label="NALVIUM, accueil">NALVIUM<span>®</span></Link><nav className="desktop-nav" aria-label="Navigation principale"><Link href="/comment-ca-marche">Comment ça marche</Link><Link href="/ma-maison">Ma maison</Link><Link href="/guides">Guides</Link><Link href="/securite">Sécurité</Link><Link href="/professionnels">Professionnels</Link></nav><Link className="header-cta" href="/comment-ca-marche">Essayer NALVIUM <Icon name="arrow" /></Link><MobileMenu /></header> }

export function Footer() { return <footer className="footer footer-v5"><div className="footer-brand"><Link className="logo" href="/">NALVIUM<span>®</span></Link><p>Comprendre d’abord. Agir avec prudence.</p><a href="mailto:contact@nalvium.com">contact@nalvium.com</a><StoreBadges /></div><div className="footer-columns"><div><small>PRODUIT</small><Link href="/comment-ca-marche">Comment ça marche</Link><Link href="/ma-maison">Ma maison</Link><Link href="/professionnels">Professionnels</Link><Link href="/securite">Sécurité</Link></div><div><small>AIDE</small><Link href="/guides">Guides</Link><Link href="/guides/plomberie">Plomberie</Link><Link href="/guides/electromenager">Électroménager</Link><Link href="/guides/bricolage">Bricolage</Link><Link href="/guides/electricite">Électricité</Link></div><div><small>LÉGAL</small><Link href="/mentions-legales">Mentions légales</Link><Link href="/confidentialite">Confidentialité</Link><Link href="/cookies">Cookies</Link><Link href="/cgu">CGU</Link><Link href="/suppression-compte">Suppression du compte</Link></div></div><small className="footer-bottom">© {new Date().getFullYear()} 3E Technology Ltd. Tous droits réservés. · NALVIUM est une marque de 3E Technology Ltd.</small></footer> }

export function ButtonLink({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) { return <Link className={secondary ? 'button button-secondary' : 'button'} href={href}>{children}{!secondary && <Icon name="arrow" />}</Link> }

export function AppDemo({ compact = false }: { compact?: boolean }) { return <div className={`demo-wrap ${compact ? 'demo-compact' : ''}`}><div className="demo-note note-top"><span className="live-dot" />Exemple d’observation</div><div className="phone"><div className="phone-bar"><span>9:41</span><span className="phone-signal">•••　▰</span></div><div className="phone-appbar"><span className="app-mark">N</span><span>NALVIUM</span><span className="app-menu">•••</span></div><div className="leak-scene"><Image src={photoAssets.leakUnderSink.src} alt={photoAssets.leakUnderSink.alt} fill sizes="(max-width: 850px) 290px, 330px" quality={78} className="phone-photo" /></div><div className="analysis"><div className="analysis-status"><span className="status-check"><Icon name="check" /></span><span>J’observe ce qui est visible…</span></div><h3>La bonde et la zone d’évacuation sont visibles.</h3><p>Je ne peux pas encore confirmer la cause. Vérifions un point simple.</p><div className="question"><small>QUESTION 01 / 02</small><strong>L’eau apparaît-elle uniquement lorsque l’eau coule ?</strong><div className="answers"><button>Oui</button><button>Non</button></div></div><div className="safe-line"><Icon name="shield" /> Une action à la fois, sans démontage.</div></div></div><div className="demo-note note-bottom"><span className="step-line" /><span>Observer <b>→</b> vérifier <b>→</b> décider</span></div></div> }

export function StoreBadges() { return <div className="store-badges" aria-label="Télécharger NALVIUM"><div className={`store-badge ${storeLinks.appStoreUrl ? '' : 'is-disabled'}`} aria-label={storeLinks.appStoreUrl ? 'Télécharger NALVIUM dans l’App Store' : 'Badge App Store à activer'}>{storeLinks.appStoreUrl ? <a href={storeLinks.appStoreUrl}><Image src="/images/stores/app-store-badge-fr.svg" alt="Télécharger dans l’App Store" width={158} height={50} /></a> : <Image src="/images/stores/app-store-badge-fr.svg" alt="App Store — lien à activer" width={158} height={50} />}</div><div className={`store-badge ${storeLinks.googlePlayUrl ? '' : 'is-disabled'}`} aria-label={storeLinks.googlePlayUrl ? 'Télécharger NALVIUM sur Google Play' : 'Badge Google Play à activer'}>{storeLinks.googlePlayUrl ? <a href={storeLinks.googlePlayUrl}><Image src="/images/stores/google-play-badge-fr.png" alt="Disponible sur Google Play" width={162} height={63} /></a> : <Image src="/images/stores/google-play-badge-fr.png" alt="Google Play — lien à activer" width={162} height={63} />}</div><span className="store-caption">Gratuit pour les particuliers</span></div> }

type CameraSceneProps = { compact?: boolean; showAction?: boolean; label?: string; priority?: boolean };
export function CameraScene({ compact = false, label = 'PHOTO DE LA SITUATION', priority = false }: CameraSceneProps) { return <div className={`camera-scene ${compact ? 'is-compact' : ''}`}><div className="scene-image"><Image src={photoAssets.leakUnderSink.src} alt={photoAssets.leakUnderSink.alt} fill sizes="(max-width: 850px) 100vw, 58vw" priority={priority} quality={82} className="scene-photo" /></div><div className="camera-top"><span>{label}</span></div></div> }

export function ObservationDemo() { return <section className="observation-demo"><div className="observation-heading"><span className="eyebrow">À TRAVERS NALVIUM</span><h2>NALVIUM ne donne pas une réponse magique.<br /><em>Il réduit l’incertitude, étape par étape.</em></h2></div><div className="observation-stage"><CameraScene showAction={false} /><div className="observation-panel"><div className="panel-label"><span>01</span> OBSERVATION <b>VISIBLE</b></div><h3>Présence d’eau au niveau du raccord inférieur.</h3><p>Pas encore un diagnostic.</p><div className="panel-question"><small>À VOUS</small><strong>La fuite apparaît-elle uniquement quand l’eau coule&nbsp;?</strong><div><button>Oui</button><button>Non</button><button>Je ne sais pas</button></div></div></div></div></section> }

export function ProblemGallery() { const items = [{ slug: 'fuite-sous-evier', title: 'Ça fuit sous l’évier', image: photoAssets.leakUnderSink, className: 'gallery-large' }, { slug: 'chasse-eau-qui-coule', title: 'La chasse d’eau coule', image: photoAssets.toilet, className: 'gallery-wide' }, { slug: 'lave-linge-ne-vidange-plus', title: 'Le lave-linge ne vidange plus', image: photoAssets.washingMachine, className: 'gallery-tall' }, { slug: 'evier-bouche', title: 'L’évier est bouché', image: photoAssets.cloggedSink, className: 'gallery-small' }].map(item => <Link key={item.slug} href={`/guides/${item.slug}`} className={`gallery-item ${item.className}`}><div className="gallery-photo"><Image src={item.image.src} alt={item.image.alt} fill sizes="(max-width: 430px) 100vw, (max-width: 850px) 50vw, 40vw" quality={78} className="gallery-photo-image" /></div><span>{item.title} <Icon name="arrow" /></span></Link>); return <div className="problem-gallery">{items}</div> }

export function Breadcrumbs({ items }: { items: { label: string; href?: string }[] }) { const allItems = [{ label: 'Accueil', href: '/' }, ...items]; const jsonLd = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: allItems.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.label, ...(item.href ? { item: `https://nalvium.com${item.href}` } : {}) })) }; return <><nav className="breadcrumbs" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link>{items.map((item) => <span key={item.label}>/ {item.href ? <Link href={item.href}>{item.label}</Link> : item.label}</span>)}</nav><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></> }

export function GuideCard({ guide }: { guide: Guide }) { return <Link className="guide-card" href={`/guides/${guide.slug}`}><span className="card-kicker">{guide.category}</span><h3>{guide.title}</h3><p>{guide.quickAnswer}</p><span className="read-link">Lire le guide <Icon name="arrow" /></span></Link> }

export function SafetyStrip() { return <section className="safety-strip"><Icon name="shield" /><div><strong>La sécurité passe avant la réparation.</strong><p>Gaz, fumée, fils exposés, eau près d’une installation électrique ou fuite importante : NALVIUM arrête le guidage DIY et recommande une orientation adaptée.</p></div><Link href="/securite">Voir nos limites <Icon name="arrow" /></Link></section> }

export function FAQ({ items }: { items: { question: string; answer: string }[] }) { return <div className="faq">{items.map((item) => <details key={item.question}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</div> }

export function SiteCta({ title = 'Montrez le problème. NALVIUM vous guide.' }: { title?: string }) { return <section className="final-cta" id="diagnostic"><div><span className="eyebrow">GRATUIT POUR LES PARTICULIERS</span><h2>{title}</h2><p>Une photo suffit pour commencer. Vous gardez le contrôle à chaque étape.</p></div><div className="final-cta-actions"><ButtonLink href="/comment-ca-marche">Essayer NALVIUM</ButtonLink><StoreBadges /></div></section> }

export function RelatedGuides({ slugs }: { slugs: string[] }) { return <div className="related-grid">{slugs.map((slug) => guideBySlug[slug]).filter(Boolean).map((guide) => <GuideCard key={guide.slug} guide={guide} />)}</div> }

export function PageHero({ eyebrow, title, children, actions, image }: { eyebrow: string; title: React.ReactNode; children?: React.ReactNode; actions?: React.ReactNode; image?: { src: string; alt: string } }) { return <section className={`page-hero-v5 ${image ? 'has-image' : ''}`}><div className="page-hero-v5-copy"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{children && <div className="page-hero-v5-body">{children}</div>}{actions && <div className="actions">{actions}</div>}</div>{image && <div className="page-hero-v5-image"><Image src={image.src} alt={image.alt} fill sizes="(max-width: 850px) 100vw, 52vw" priority quality={82} /></div>}</section> }

export function SectionHeader({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: React.ReactNode }) { return <div className="section-header-v5">{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{children && <div className="section-header-v5-body">{children}</div>}</div> }

export function SafetyStop({ items, title = 'STOP IMMÉDIAT' }: { items: string[]; title?: string }) { return <section className="safety-stop"><div className="safety-stop-mark"><Icon name="shield" /></div><div><span className="eyebrow">{title}</span><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></div></section> }

export function ProfessionalHandoff() { return <section className="professional-handoff"><div><span className="eyebrow">PASSAGE AU PROFESSIONNEL</span><h2>Quand il faut passer la main, vous n’arrivez pas les mains vides.</h2><p>Vous choisissez ce que vous transmettez. Le contexte observé aide à commencer une conversation plus précise, sans remplacer le diagnostic du professionnel.</p></div><div className="handoff-file handoff-note"><span className="eyebrow">CONTEXTE CHOISI</span><strong>Vous gardez la main sur les informations transmises.</strong><Link href="/professionnels">Comprendre le passage au professionnel <Icon name="arrow" /></Link></div></section> }

export function GuidePhoto({ guide, priority = false }: { guide: Guide; priority?: boolean }) { const image = guideImage(guide.slug); return <div className="guide-photo"><Image src={image.src} alt={image.alt} fill sizes="(max-width: 850px) 100vw, 42vw" priority={priority} quality={80} /></div> }

export function guideImage(slug: string) { if (slug.includes('wc-') || slug.includes('chasse')) return photoAssets.toilet; if (slug.includes('robinet')) return photoAssets.leakingFaucet; if (slug.includes('evier') || slug.includes('canalisation') || slug.includes('odeur')) return photoAssets.cloggedSink; if (slug.includes('fuite')) return photoAssets.leakUnderSink; if (slug.includes('lave-linge') || slug.includes('machine')) return photoAssets.washingMachineDrain; if (slug.includes('lave-vaisselle') || slug.includes('vaisselle')) return photoAssets.dishwasher; if (slug.includes('four')) return photoAssets.oven; if (slug.includes('refrigerateur')) return photoAssets.refrigerator; if (slug.includes('groupe-securite')) return photoAssets.waterHeater; return photoAssets.leakUnderSink; }

export function PhotoBand({ eyebrow, title, text, image, light = false, reverse = false, children }: { eyebrow: string; title: string; text: string; image: { src: string; alt: string }; light?: boolean; reverse?: boolean; children?: React.ReactNode }) { return <section className={`photo-band ${light ? 'is-light' : ''} ${reverse ? 'is-reverse' : ''}`}><div className="photo-band-image"><Image src={image.src} alt={image.alt} fill sizes="(max-width: 850px) 100vw, 50vw" quality={80} /></div><div className="photo-band-copy"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p>{children}</div></section> }

export function ProductSequence({ steps }: { steps: { number: string; title: string; text: string; image?: { src: string; alt: string } }[] }) { return <div className="product-sequence">{steps.map((step, index) => <div className="product-sequence-step" key={step.number}><div className="product-sequence-photo">{step.image ? <Image src={step.image.src} alt={step.image.alt} fill sizes="(max-width: 850px) 100vw, 31vw" quality={78} /> : <div className="product-sequence-empty" aria-hidden="true" />}<span className="sequence-index">{step.number}</span></div><div><span className="eyebrow">{step.number} · {step.title}</span><p>{step.text}</p></div>{index < steps.length - 1 && <span className="sequence-arrow">→</span>}</div>)}</div> }

export function PhotoProblemCard({ title, image, href, size = '' }: { title: string; image: { src: string; alt: string }; href: string; size?: string }) { return <Link className={`photo-problem-card ${size}`} href={href}><div><Image src={image.src} alt={image.alt} fill sizes="(max-width: 700px) 100vw, 33vw" quality={78} /><span /></div><strong>{title}</strong><i>→</i></Link> }

export function ObservationPhoto({ image, label = 'PHOTO DE LA SITUATION' }: { image: { src: string; alt: string }; label?: string; observation?: string; question?: string }) { return <div className="observation-photo-shell"><Image src={image.src} alt={image.alt} fill sizes="(max-width:850px) 100vw, 70vw" quality={82} priority/><div className="observation-photo-top">{label}</div></div> }
