export type Guide = {
  slug: string;
  category: string;
  categorySlug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  quickAnswer: string;
  causes: string[];
  observations: string[];
  safeChecks: string[];
  safeActions: string[];
  stopConditions: string[];
  whenToCallPro: string;
  faq: { question: string; answer: string }[];
  related: string[];
  localPath?: string;
};

export const guides: Guide[] = [
  {
    slug: 'fuite-sous-evier', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/fuite-eau',
    title: 'Fuite sous évier : que vérifier sans prendre de risque ?', metaTitle: 'Fuite sous évier : vérifications sûres | NALVIUM', metaDescription: 'Fuite sous évier : observez le raccord, le siphon et le moment où l’eau apparaît avant toute intervention, avec des vérifications sûres.',
    intro: 'Une flaque sous l’évier ne suffit pas à connaître l’origine de l’eau. Le premier indice est souvent le moment où la première goutte apparaît, sans démonter.',
    quickAnswer: 'Placez un récipient stable, séchez uniquement l’extérieur et observez si l’eau revient quand le robinet coule ou même au repos. Si le débit augmente ou si l’eau approche une installation électrique, arrêtez-vous.',
    causes: ['Un raccord du siphon ou de l’évacuation peut laisser passer de l’eau', 'Un joint ou un flexible peut être humide', 'La fuite peut venir du robinet et descendre plus bas', 'Un refoulement peut donner l’impression d’une fuite sous le meuble'],
    observations: ['Le premier point humide, et non la zone où l’eau finit', 'Fuite permanente ou seulement pendant l’utilisation', 'Eau claire, stagnante ou issue d’un refoulement', 'Prise, multiprise ou appareil alimenté à proximité'],
    safeChecks: ['Éloigner les objets uniquement si la zone reste sèche et accessible', 'Placer un récipient sans mettre les mains dans l’eau', 'Sécher l’extérieur d’un raccord puis regarder où l’humidité revient', 'Fermer l’arrivée d’eau seulement si elle est identifiable et tourne sans forcer'],
    safeActions: ['Photographier le dessous de l’évier et le raccord visible', 'Faire couler une très petite quantité d’eau uniquement si aucune installation électrique n’est exposée', 'Noter si l’eau apparaît au repos'],
    stopConditions: ['Fuite importante ou impossible à contenir', 'Eau proche d’une prise, d’une multiprise ou d’un appareil alimenté', 'Raccord corrodé, fissuré ou résistant', 'Origine impossible à suivre sans déplacer ou démonter'],
    whenToCallPro: 'Un professionnel pourra rechercher l’origine exacte, vérifier les raccords et contrôler les dommages éventuels. NALVIUM aide à préparer les observations, pas à confirmer la panne.',
    faq: [{ question: 'Pourquoi l’eau apparaît-elle seulement quand le robinet coule ?', answer: 'Cela peut orienter vers l’évacuation, le siphon ou un raccord sollicité par le débit. L’observation ne permet pas à elle seule de confirmer la cause.' }, { question: 'Puis-je démonter le siphon ?', answer: 'Pas comme première étape. S’il y a un produit chimique, une fuite importante, de l’électricité proche ou un raccord qui résiste, ne démontez pas.' }, { question: 'Que faire si je ne vois pas l’origine ?', answer: 'Photographiez la zone, notez quand l’humidité revient et arrêtez les essais si vous devez ouvrir, forcer ou toucher une zone dangereuse.' }], related: ['fuite-sous-lavabo', 'robinet-qui-fuit-a-la-base', 'robinet-qui-goutte', 'evier-bouche'],
  },
  {
    slug: 'robinet-qui-goutte', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/robinet-qui-fuit',
    title: 'Robinet qui goutte : comprendre avant d’intervenir', metaTitle: 'Robinet qui goutte : premières vérifications | NALVIUM', metaDescription: 'Robinet qui goutte : distinguez le bec, la base et le raccord, puis vérifiez uniquement ce qui reste accessible et sans danger.', intro: 'Le point où la goutte tombe n’est pas forcément le point où l’eau entre. Séchez les surfaces et observez le robinet fermé puis ouvert, sans forcer.',
    quickAnswer: 'Regardez si la goutte vient du bec, de la base ou d’un flexible. Une goutte au bec ne se vérifie pas comme une humidité dans le meuble ; une poignée bloquée ou une fuite importante doit faire arrêter les essais.',
    causes: ['Un mécanisme interne peut ne plus fermer complètement', 'Un joint ou un flexible visible peut être humide', 'Un dépôt peut gêner l’aérateur', 'L’eau peut venir d’un raccord et ruisseler vers la base'],
    observations: ['Bec, base, dessous du meuble ou raccord', 'Gouttes robinet fermé, ouvert, ou dans les deux cas', 'Variation après quelques secondes d’utilisation', 'Eau près d’une prise ou d’un appareil'],
    safeChecks: ['Sécher uniquement les surfaces extérieures', 'Ouvrir puis fermer doucement sans forcer', 'Observer un flexible sans le déplacer', 'Fermer l’arrivée si elle est accessible et la fuite augmente'],
    safeActions: ['Photographier le bec, la base et les raccords', 'Nettoyer seulement l’aérateur extérieur si l’origine est clairement là', 'Comparer l’endroit de la première humidité et celui de la goutte'],
    stopConditions: ['Fuite importante ou eau dans le meuble', 'Raccord corrodé ou déformé', 'Eau proche d’une installation électrique', 'Poignée bloquée ou mécanisme à démonter'],
    whenToCallPro: 'Un professionnel est préférable si le mécanisme interne, la cartouche ou un raccord doit être démonté. NALVIUM ne transforme pas l’observation en diagnostic.',
    faq: [{ question: 'Un robinet qui goutte vient-il forcément du joint ?', answer: 'Non. Parmi les causes possibles figurent un mécanisme interne, un raccord, un flexible ou un dépôt autour de l’aérateur.' }, { question: 'Pourquoi le robinet goutte-t-il même fermé ?', answer: 'Observez si l’eau vient du bec, de la base ou d’un raccord. Cette distinction oriente la suite sans confirmer la cause.' }, { question: 'Puis-je resserrer le robinet ?', answer: 'Seulement si un raccord est manifestement accessible et se ferme sans effort. N’utilisez pas de force et ne démontez pas le mécanisme.' }], related: ['robinet-qui-fuit-a-la-base', 'fuite-sous-evier', 'fuite-sous-lavabo', 'evier-bouche'],
  },
  {
    slug: 'chasse-eau-qui-coule', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/chasse-eau',
    title: 'Chasse d’eau qui coule : les vérifications sûres', metaTitle: 'Chasse d’eau qui coule : que vérifier ? | NALVIUM', metaDescription: 'Chasse d’eau qui coule : observez le flotteur, le mécanisme et le filet d’eau sans démontage risqué, puis sachez quand arrêter.', intro: 'Un bruit de remplissage et un filet d’eau dans la cuvette ne donnent pas les mêmes indices. Commencez par observer le réservoir fermé, sans forcer le bouton ni le robinet.',
    quickAnswer: 'Écoutez si l’eau continue d’entrer après la chasse et regardez si elle passe dans la cuvette ou fuit autour du réservoir. Fermez l’arrivée seulement si elle tourne normalement.',
    causes: ['Le flotteur peut ne plus fermer l’arrivée', 'Le clapet ou joint peut laisser passer de l’eau vers la cuvette', 'Le bouton peut rester en tension', 'Le réservoir ou un raccord peut fuir vers l’extérieur'],
    observations: ['Bruit de remplissage continu ou intermittent', 'Filet d’eau dans la cuvette', 'Position visible du flotteur et retour du bouton', 'Trace d’eau autour du réservoir'],
    safeChecks: ['Fermer le petit robinet si l’eau coule beaucoup et qu’il est accessible', 'Observer le mécanisme sans débrancher ni forcer', 'Retirer le couvercle uniquement s’il se soulève sans résistance'],
    safeActions: ['Photographier le mécanisme visible', 'Noter si le bruit cesse quand l’arrivée est fermée', 'Nettoyer une surface extérieure sans produit agressif'],
    stopConditions: ['Robinet d’arrêt bloqué', 'Réservoir fissuré ou fuite extérieure', 'Eau proche d’un équipement électrique', 'Besoin de démonter ou forcer une pièce'],
    whenToCallPro: 'Un professionnel pourra identifier le mécanisme compatible et vérifier l’étanchéité. NALVIUM aide à décrire le symptôme, pas à garantir une réparation.',
    faq: [{ question: 'Puis-je régler le flotteur ?', answer: 'Seulement si un réglage est clairement prévu et accessible. Arrêtez-vous si vous ne reconnaissez pas le mécanisme ou s’il faut forcer.' }, { question: 'Pourquoi l’eau coule-t-elle dans la cuvette ?', answer: 'Le clapet, le joint ou le niveau d’eau peuvent être en cause parmi d’autres possibilités. Observez le filet sans démonter.' }], related: ['wc-qui-remonte', 'wc-se-vide-lentement', 'canalisation-qui-glougloute', 'fuite-sous-evier'],
  },
  {
    slug: 'evier-bouche', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/evier-bouche',
    title: 'Évier bouché : quoi essayer sans mélanger de produits ?', metaTitle: 'Évier bouché : vérifications et gestes sûrs | NALVIUM', metaDescription: 'Évier bouché : distinguez bonde, siphon et évacuation plus loin, sans mélange chimique et sans démontage risqué.', intro: 'Une eau stagnante peut rester près de la bonde ou signaler une évacuation plus lente. La présence d’un autre équipement touché change la prudence à adopter.',
    quickAnswer: 'N’ajoutez pas d’eau si le niveau monte. Retirez uniquement les débris visibles, vérifiez si un produit a déjà été versé et n’utilisez jamais de mélange chimique.',
    causes: ['Débris ou graisse près de la bonde', 'Siphon encombré', 'Bouchon plus loin dans la branche', 'Réseau plus général si plusieurs évacuations sont touchées'],
    observations: ['Écoulement lent ou totalement bloqué', 'Eau qui remonte ou refoule', 'Mauvaise odeur ou glouglou', 'Évier seul ou plusieurs équipements concernés'],
    safeChecks: ['Limiter l’eau ajoutée et protéger le meuble', 'Retirer les débris visibles avec des gants adaptés', 'Observer le dessous sans démonter', 'Vérifier si un déboucheur est déjà présent'],
    safeActions: ['Utiliser une ventouse seulement sans produit chimique', 'Photographier la bonde, le siphon visible et l’eau stagnante', 'Noter si le niveau change sans utilisation'],
    stopConditions: ['Produit chimique présent ou inconnu', 'Refoulement important ou eau potentiellement contaminée', 'Fuite du siphon ou raccord qui résiste', 'Plusieurs évacuations touchées'],
    whenToCallPro: 'Un professionnel est préférable si le bouchon est profond, récurrent, accompagné d’un refoulement ou si une pièce doit être démontée.',
    faq: [{ question: 'Puis-je mélanger vinaigre et déboucheur ?', answer: 'Non. Ne mélangez jamais des produits ménagers ou déboucheurs : arrêtez-vous si un produit est déjà présent.' }, { question: 'Comment savoir si le bouchon est plus loin ?', answer: 'Un écoulement lent sur plusieurs équipements, des glouglous ou un refoulement peuvent orienter vers une obstruction plus loin, sans le prouver.' }], related: ['evier-se-vide-lentement', 'canalisation-qui-glougloute', 'mauvaise-odeur-canalisation', 'fuite-sous-evier'],
  },
  {
    slug: 'wc-qui-remonte', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/wc-bouche',
    title: 'WC qui remonte : que faire quand l’eau monte dans les toilettes ?', metaTitle: 'WC qui remonte : premières vérifications | NALVIUM', metaDescription: 'WC qui remonte : distinguez obstruction locale et évacuation plus générale avant d’agir, sans mélange chimique ni débordement.', intro: 'Une eau qui monte dans la cuvette peut rester liée au WC ou concerner une évacuation plus loin. Le premier objectif est d’éviter le débordement.', quickAnswer: 'N’ajoutez pas d’eau et arrêtez la chasse. Observez si seul le WC est touché ou si douche, lavabo ou évier ralentissent aussi. Un refoulement important impose d’arrêter les essais.',
    causes: ['Une obstruction locale de la cuvette ou de sa sortie', 'Une évacuation ralentie après la chasse', 'Un problème plus loin si plusieurs équipements refoulent', 'Un produit déjà versé pouvant rendre toute manipulation dangereuse'], observations: ['L’eau monte puis redescend ou reste haute', 'WC seul ou plusieurs évacuations touchées', 'Glouglou, odeur inhabituelle ou eau trouble', 'Apparition après une chasse ou sans utilisation'], safeChecks: ['Ne pas relancer la chasse et fermer l’arrivée si elle est accessible sans forcer', 'Protéger le sol sans toucher à l’eau potentiellement contaminée', 'Observer les autres évacuations sans ajouter d’eau', 'Vérifier si un produit chimique a été utilisé'], safeActions: ['Utiliser une ventouse seulement si aucun produit chimique n’est présent et si le niveau reste maîtrisable', 'Photographier le niveau et noter les autres équipements concernés'], stopConditions: ['Débordement ou refoulement important', 'Eau potentiellement contaminée', 'Plusieurs évacuations touchées', 'Produit chimique présent ou besoin de démonter'], whenToCallPro: 'Demandez une aide professionnelle si le niveau ne baisse pas, si plusieurs équipements sont concernés ou si le risque sanitaire augmente.', faq: [{ question: 'Pourquoi l’eau remonte-t-elle dans les WC ?', answer: 'Cela peut venir d’une obstruction locale ou d’une évacuation plus loin. Le fait que d’autres équipements soient touchés est une information importante, pas une preuve.' }, { question: 'Puis-je tirer la chasse une deuxième fois ?', answer: 'Non si le niveau monte ou redescend mal : ajoutez le moins d’eau possible et observez avant de poursuivre.' }], related: ['wc-se-vide-lentement', 'chasse-eau-qui-coule', 'canalisation-qui-glougloute', 'evier-bouche'],
  },
  {
    slug: 'wc-se-vide-lentement', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/wc-bouche',
    title: 'WC qui se vide lentement : causes possibles et vérifications sûres', metaTitle: 'WC qui se vide lentement : que vérifier ? | NALVIUM', metaDescription: 'WC qui se vide lentement : observez le niveau, le bruit et les autres évacuations avant d’essayer quoi que ce soit.', intro: 'Une cuvette qui se vide lentement peut annoncer une obstruction locale ou une évacuation ralentie plus loin. Comparez les signes avant de multiplier les essais.', quickAnswer: 'Notez le temps d’écoulement, l’évolution du niveau et l’état de douche ou lavabo. Si l’eau remonte, sent mauvais ou refoule, arrêtez les essais.', causes: ['Un passage partiellement obstrué dans le WC', 'Une évacuation qui s’encrasse plus loin', 'Un problème plus général si plusieurs appareils ralentissent', 'Un niveau d’eau inhabituel lié au mécanisme ou à l’arrivée'], observations: ['Niveau après la chasse et vitesse de baisse', 'Bruit de glouglou ou odeur', 'WC seul ou plusieurs points concernés', 'Récurrence à chaque utilisation ou seulement parfois'], safeChecks: ['Limiter les chasses répétées', 'Observer les autres évacuations sans ajouter d’eau', 'Fermer l’arrivée si le niveau monte et si la commande est sûre', 'Vérifier qu’aucun produit chimique n’a été versé'], safeActions: ['Utiliser une ventouse adaptée uniquement sans produit chimique', 'Photographier le niveau et noter quand le ralentissement apparaît'], stopConditions: ['Eau qui déborde ou refoule', 'Plusieurs équipements touchés', 'Produit chimique présent ou inconnu', 'Besoin de démonter ou forcer'], whenToCallPro: 'Un professionnel est préférable si le ralentissement devient récurrent, touche plusieurs évacuations ou s’accompagne d’un refoulement.', faq: [{ question: 'Un WC lent est-il forcément bouché ?', answer: 'Non. Une obstruction partielle est possible, mais d’autres éléments du réseau ou du mécanisme peuvent produire un symptôme proche.' }, { question: 'Quand arrêter les essais ?', answer: 'Arrêtez si le niveau monte, si plusieurs équipements sont touchés, si un produit est présent ou si une manipulation nécessite de forcer.' }], related: ['wc-qui-remonte', 'canalisation-qui-glougloute', 'chasse-eau-qui-coule'],
  },
  {
    slug: 'canalisation-qui-glougloute', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/canalisation-bouchee',
    title: 'Pourquoi ma canalisation fait-elle glouglou ?', metaTitle: 'Canalisation qui glougloute : que vérifier ? | NALVIUM', metaDescription: 'Canalisation glouglou : distinguez bruit isolé, écoulement lent, odeur et refoulement avec des observations sans danger.', intro: 'Un glouglou indique seulement qu’un bruit inhabituel accompagne l’écoulement. Il peut rester local ou apparaître sur plusieurs évacuations : comparez les signes.', quickAnswer: 'Notez quel équipement fait le bruit, à quel moment et si l’eau s’évacue lentement. Vérifiez si WC, douche ou lavabo sont également concernés, sans faire couler beaucoup d’eau pour tester.', causes: ['De l’air peut accompagner un écoulement ralenti', 'Un siphon ou une bonde peut être encombré', 'Une obstruction plus loin peut toucher plusieurs branches', 'Une odeur ou un refoulement peut signaler une situation plus urgente'], observations: ['Un seul point d’eau ou plusieurs', 'Bruit après l’utilisation de quel équipement', 'Écoulement normal ou ralenti', 'Odeur, niveau qui monte ou refoulement'], safeChecks: ['Écouter sans démonter ni verser de produit', 'Noter l’ordre des équipements concernés', 'Limiter les essais avec de grandes quantités d’eau', 'Photographier un niveau ou refoulement sans toucher l’eau'], safeActions: ['Retirer seulement les débris visibles d’une bonde accessible', 'Utiliser une ventouse uniquement sans produit chimique et si aucun refoulement important n’existe'], stopConditions: ['Refoulement d’eau usée ou risque sanitaire', 'Plusieurs équipements touchés', 'Débordement', 'Produit chimique présent ou raccord à démonter'], whenToCallPro: 'Demandez une aide professionnelle si le bruit devient accompagné d’un ralentissement, d’une odeur persistante ou d’un refoulement.', faq: [{ question: 'Un glouglou signifie-t-il que la canalisation est bouchée ?', answer: 'Pas forcément. Le bruit peut accompagner plusieurs situations ; la vitesse d’écoulement et le nombre d’équipements touchés apportent des indices complémentaires.' }, { question: 'Pourquoi l’évier fait-il glouglou après la chasse ?', answer: 'Un bruit après l’utilisation d’un autre équipement est une information à noter, car plusieurs évacuations peuvent communiquer. Cela ne suffit pas à confirmer la cause.' }], related: ['evier-bouche', 'evier-se-vide-lentement', 'mauvaise-odeur-canalisation', 'wc-qui-remonte'],
  },
  {
    slug: 'mauvaise-odeur-canalisation', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/canalisation-bouchee',
    title: 'Mauvaise odeur de canalisation : que peut-elle indiquer ?', metaTitle: 'Mauvaise odeur canalisation : vérifications sûres | NALVIUM', metaDescription: 'Mauvaise odeur de canalisation : localisez le point, observez l’écoulement et sachez quand arrêter sans utiliser de mélange dangereux.', intro: 'Une odeur peut venir d’un siphon, de résidus ou d’une évacuation ralentie. Elle ne permet pas de confirmer l’origine : commencez par la localiser.', quickAnswer: 'Comparez les équipements, notez si l’odeur apparaît après l’écoulement et vérifiez s’il existe un glouglou ou un refoulement. N’utilisez pas de mélange chimique.', causes: ['Des résidus peuvent rester près de la bonde', 'Un siphon peut être encrassé ou mal alimenté en eau', 'Une évacuation ralentie peut retenir des matières', 'Une odeur avec refoulement peut signaler une situation plus générale'], observations: ['Équipement précis et moment d’apparition', 'Odeur seule ou avec écoulement lent', 'Glouglou, niveau qui monte ou refoulement', 'Un seul point ou plusieurs évacuations'], safeChecks: ['Aérer la pièce et observer sans mettre le visage au-dessus de l’évacuation', 'Retirer uniquement les résidus visibles', 'Faire couler peu d’eau seulement si aucun refoulement n’est présent', 'Vérifier si un produit chimique a déjà été utilisé'], safeActions: ['Nettoyer extérieurement la bonde avec des gants adaptés', 'Noter l’évolution de l’odeur après une utilisation normale'], stopConditions: ['Odeur de gaz ou fumée', 'Eau usée qui refoule', 'Produit chimique inconnu', 'Plusieurs évacuations fortement touchées'], whenToCallPro: 'Une aide professionnelle est préférable si l’odeur persiste, si elle s’accompagne d’un refoulement ou si l’origine est inaccessible.', faq: [{ question: 'Une mauvaise odeur signifie-t-elle que la canalisation est bouchée ?', answer: 'Non. Des résidus, un siphon ou une évacuation ralentie sont parmi les possibilités. Le ralentissement et le refoulement sont des indices séparés.' }, { question: 'Puis-je verser plusieurs produits pour supprimer l’odeur ?', answer: 'Non. Ne mélangez jamais des produits ménagers ou déboucheurs ; arrêtez-vous si un produit est déjà présent.' }], related: ['canalisation-qui-glougloute', 'evier-bouche', 'evier-se-vide-lentement'],
  },
  {
    slug: 'evier-se-vide-lentement', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/evier-bouche',
    title: 'Évier qui se vide lentement : comment orienter les vérifications ?', metaTitle: 'Évier se vide lentement : que vérifier ? | NALVIUM', metaDescription: 'Évier qui se vide lentement : distinguez bonde, siphon et problème plus général sans mélanger de produits.', intro: 'Une évacuation lente peut rester locale ou correspondre à un bouchon plus loin. Le nombre d’équipements concernés et la présence d’un glouglou sont utiles à noter.', quickAnswer: 'Limitez l’eau, observez si le niveau redescend et regardez si douche ou WC sont également lents. Ne démontez pas si un produit chimique est présent.', causes: ['Bonde encombrée par des résidus', 'Siphon ralenti', 'Obstruction dans la canalisation en aval', 'Réseau plus général si plusieurs équipements sont touchés'], observations: ['Temps de vidange et niveau d’eau', 'Odeur, glouglou ou refoulement', 'Évier seul ou autres évacuations', 'Apparition progressive ou brutale'], safeChecks: ['Retirer les débris visibles avec des gants', 'Limiter l’eau ajoutée', 'Observer le siphon sans le démonter', 'Vérifier la présence éventuelle d’un produit'], safeActions: ['Utiliser une ventouse seulement sans produit chimique', 'Photographier la bonde et noter les autres symptômes'], stopConditions: ['Refoulement ou eau potentiellement contaminée', 'Plusieurs équipements touchés', 'Produit chimique présent', 'Fuite ou raccord qui résiste'], whenToCallPro: 'Faites intervenir un professionnel si le ralentissement persiste, revient régulièrement ou concerne plusieurs évacuations.', faq: [{ question: 'Comment savoir si le siphon est en cause ?', answer: 'Un ralentissement isolé près d’un évier peut orienter vers la bonde ou le siphon, mais seule une observation extérieure ne permet pas de confirmer.' }, { question: 'Pourquoi l’évier fait-il glouglou ?', answer: 'Le bruit peut accompagner un écoulement ralenti ou une autre situation. Notez si le WC ou la douche sont aussi concernés.' }], related: ['evier-bouche', 'canalisation-qui-glougloute', 'mauvaise-odeur-canalisation', 'fuite-sous-evier'],
  },
  {
    slug: 'fuite-sous-lavabo', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/fuite-eau',
    title: 'Fuite sous lavabo : que vérifier avant de démonter ?', metaTitle: 'Fuite sous lavabo : vérifications sûres | NALVIUM', metaDescription: 'Fuite sous lavabo : localisez la première goutte, distinguez robinet et évacuation et sachez quand arrêter sans démontage risqué.', intro: 'Sous un lavabo, l’eau peut venir du robinet, d’un flexible, du siphon ou d’une fuite située plus haut. Suivez l’eau sans confondre son point d’arrivée avec son origine.', quickAnswer: 'Séchez l’extérieur, placez un récipient et observez si la fuite apparaît au repos ou seulement quand le lavabo coule. Si l’eau approche l’électricité, arrêtez-vous.', causes: ['Flexible ou raccord d’arrivée humide', 'Siphon ou évacuation qui fuit pendant l’écoulement', 'Joint de bonde ou robinet humide', 'Eau provenant d’une zone située au-dessus'], observations: ['Première zone humide', 'Fuite permanente ou liée à l’utilisation', 'Eau claire, stagnante ou refoulée', 'Prise ou appareil dans la zone'], safeChecks: ['Éloigner les objets sans toucher une zone électrique humide', 'Placer un récipient stable', 'Sécher les surfaces accessibles', 'Fermer l’eau si la commande est clairement accessible'], safeActions: ['Photographier les raccords visibles', 'Faire couler un filet d’eau uniquement si le contexte reste sûr', 'Noter si la fuite revient au repos'], stopConditions: ['Fuite importante', 'Eau proche d’une installation électrique', 'Raccord corrodé ou résistant', 'Besoin de démonter ou ouvrir une paroi'], whenToCallPro: 'Un professionnel pourra distinguer alimentation, robinet et évacuation puis contrôler l’étanchéité. NALVIUM aide à préparer la description.', faq: [{ question: 'Une fuite sous lavabo vient-elle forcément du siphon ?', answer: 'Non. Le robinet, un flexible, la bonde ou une zone plus haute peuvent aussi être concernés.' }, { question: 'Puis-je démonter le siphon ?', answer: 'Pas si l’origine est incertaine, si un produit chimique est présent ou si le raccord résiste.' }], related: ['fuite-sous-evier', 'robinet-qui-fuit-a-la-base', 'robinet-qui-goutte'],
  },
  {
    slug: 'robinet-qui-fuit-a-la-base', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/robinet-qui-fuit',
    title: 'Robinet qui fuit à la base : origine possible et vérifications', metaTitle: 'Robinet qui fuit à la base : que vérifier ? | NALVIUM', metaDescription: 'Robinet qui fuit à la base : observez la première zone humide et les raccords sans forcer ni démonter sous l’évier.', intro: 'Une fuite à la base peut être visible autour du corps du robinet ou venir d’un raccord voisin. Séchez, observez et comparez robinet ouvert et fermé.', quickAnswer: 'Séchez la base et le dessous, puis regardez quel endroit redevient humide en utilisant doucement le robinet. Une poignée qui force, un raccord abîmé ou de l’eau près d’une prise impose l’arrêt.', causes: ['Joint de base qui n’assure plus l’étanchéité', 'Flexible ou raccord humide sous le meuble', 'Fuite interne qui ressort par la base', 'Eau venant du bec ou d’un autre point et ruisselant'], observations: ['Base du robinet, flexible ou raccord', 'Fuite robinet ouvert, fermé, ou dans les deux cas', 'Eau dans le meuble ou seulement sur le plan', 'Présence d’un équipement électrique'], safeChecks: ['Sécher l’extérieur avec un chiffon', 'Observer sans déplacer les flexibles', 'Fermer l’arrivée si elle est accessible sans forcer', 'Photographier avant toute manipulation'], safeActions: ['Comparer le premier point humide avec le point où l’eau tombe', 'Nettoyer uniquement une surface extérieure accessible'], stopConditions: ['Fuite importante ou meuble très humide', 'Eau proche d’électricité', 'Raccord corrodé, poignée bloquée ou besoin d’outil', 'Nécessité de retirer le robinet'], whenToCallPro: 'Le remplacement d’un joint ou le démontage du robinet doit être confié à un professionnel si l’accès ou l’origine ne sont pas évidents.', faq: [{ question: 'Pourquoi l’eau fuit-elle à la base du robinet ?', answer: 'Un joint, un flexible, un raccord ou une fuite interne peuvent produire une humidité similaire. L’emplacement de la première goutte aide à orienter sans confirmer.' }, { question: 'Puis-je resserrer l’écrou sous le lavabo ?', answer: 'Pas si l’accès est humide, si le raccord résiste ou si vous ne savez pas quelle pièce vous touchez.' }], related: ['robinet-qui-goutte', 'fuite-sous-lavabo', 'fuite-sous-evier'],
  },
  {
    slug: 'groupe-securite-chauffe-eau-qui-coule', category: 'Plomberie', categorySlug: 'plomberie', localPath: '/plombier/lyon/chauffe-eau',
    title: 'Groupe de sécurité du chauffe-eau qui coule : que vérifier ?', metaTitle: 'Groupe de sécurité chauffe-eau qui coule | NALVIUM', metaDescription: 'Groupe de sécurité du chauffe-eau qui coule : observez le moment, le volume et les zones humides sans toucher à l’électricité.', intro: 'Une goutte au groupe de sécurité peut apparaître pendant la chauffe, mais un écoulement important ou permanent demande une évaluation professionnelle. Ne démontez pas l’équipement.', quickAnswer: 'Observez l’extérieur, le moment où l’eau apparaît et son volume. Ne touchez ni au capot électrique, ni à une zone sous tension, ni à une installation gaz ; éloignez-vous si l’eau atteint l’électricité.', causes: ['Un écoulement lié au fonctionnement peut être possible selon l’installation', 'Le groupe, un raccord ou un joint peut être humide', 'La pression ou un composant interne peut nécessiter un contrôle', 'Une fuite de cuve peut ressembler à une fuite du groupe'], observations: ['Goutte ponctuelle ou écoulement continu', 'Fuite pendant la chauffe ou au repos', 'Point exact : groupe, raccord, cuve ou sol', 'Eau proche d’un câblage ou d’un appareil'], safeChecks: ['Observer uniquement l’extérieur', 'Placer un récipient si cela reste sûr et stable', 'Photographier les raccords et références visibles', 'Repérer l’arrivée d’eau sans tourner une commande qui résiste'], safeActions: ['Noter l’heure et l’évolution de la fuite', 'Protéger le sol sans toucher une zone électrique humide'], stopConditions: ['Eau proche d’une installation électrique', 'Fuite importante ou non maîtrisable', 'Odeur de gaz, fumée, chaleur ou bruit inquiétant', 'Capot à ouvrir ou commande à forcer'], whenToCallPro: 'Un professionnel doit examiner le groupe, la pression et la cuve lorsque l’écoulement est important, persistant ou mal localisé. NALVIUM ne guide pas une intervention sous tension ou sur le gaz.', faq: [{ question: 'Un groupe de sécurité peut-il goutter pendant la chauffe ?', answer: 'Le contexte et la quantité comptent, mais une observation extérieure ne permet pas de conclure. Notez le moment et l’évolution puis demandez conseil si cela persiste.' }, { question: 'Puis-je manipuler le groupe de sécurité ?', answer: 'Non comme première étape. Ne forcez pas une commande et ne touchez pas une installation électrique humide.' }], related: ['fuite-sous-evier', 'fuite-sous-lavabo'],
  },
  {
    slug: 'machine-a-laver-qui-fuit', category: 'Électroménager', categorySlug: 'electromenager', title: 'Machine à laver qui fuit : localiser l’eau sans danger', metaTitle: 'Machine à laver qui fuit : premières vérifications | NALVIUM', metaDescription: 'Machine à laver qui fuit : distinguez porte, bac, tuyau et dessous de l’appareil avant de demander une intervention.', intro: 'Une fuite de lave-linge peut apparaître à l’avant, à l’arrière ou seulement pendant la vidange. Commencez par sécuriser et localiser l’eau sans déplacer seul un appareil lourd.', quickAnswer: 'Arrêtez le programme, débranchez seulement si la prise et le sol sont secs et accessibles, puis notez si l’eau vient de la porte, du bac, d’un tuyau ou du dessous. Ne remettez pas sous tension une zone humide.', causes: ['Joint de hublot ou porte qui n’est plus étanche', 'Bac à lessive ou arrivée d’eau qui déborde', 'Tuyau visible plié ou raccord humide', 'Fuite pendant vidange ou essorage'], observations: ['Moment de la fuite dans le cycle', 'Avant, arrière, porte ou dessous', 'Eau claire ou chargée de lessive', 'Code erreur, bruit ou vibration inhabituelle'], safeChecks: ['Arrêter le programme', 'Débrancher uniquement à sec et sans toucher une zone mouillée', 'Fermer l’arrivée d’eau si elle est accessible sans forcer', 'Photographier le modèle et la zone humide'], safeActions: ['Essuyer uniquement le sol sec autour de l’appareil', 'Observer le joint et les tuyaux extérieurs sans tirer sur la machine'], stopConditions: ['Eau proche d’une prise ou appareil alimenté', 'Odeur de brûlé, fumée ou choc électrique', 'Appareil lourd à déplacer', 'Besoin d’ouvrir un panneau'], whenToCallPro: 'Un réparateur est préférable si la fuite vient de l’intérieur, si l’appareil doit être déplacé ou si un risque électrique existe.', faq: [{ question: 'Puis-je relancer la machine pour voir quand elle fuit ?', answer: 'Pas si le sol, la prise ou la machine sont humides. Documentez le cycle interrompu et demandez un avis.' }], related: ['lave-linge-ne-vidange-plus', 'lave-linge-nessore-plus', 'fuite-sous-evier'],
  },
  {
    slug: 'lave-linge-ne-vidange-plus', category: 'Électroménager', categorySlug: 'electromenager', title: 'Lave-linge qui ne vidange plus : que vérifier ?', metaTitle: 'Lave-linge ne vidange plus : vérifications sûres | NALVIUM', metaDescription: 'Lave-linge qui ne vidange plus : distinguez eau dans le tambour, pompe silencieuse, bruit et tuyau visible sans démontage dangereux.', intro: 'De l’eau dans le tambour peut venir d’un cycle interrompu, d’une évacuation ralentie ou d’un problème de pompe. Observez avant d’ouvrir la trappe.', quickAnswer: 'Notez le niveau d’eau, le programme interrompu, le bruit éventuel de pompe et si le tuyau visible est plié. Débranchez à sec uniquement ; n’ouvrez pas une trappe si l’eau risque de se répandre sans contrôle.', causes: ['Tuyau d’évacuation visible plié ou positionné anormalement', 'Filtre accessible encombré selon la notice', 'Pompe qui fait du bruit ou reste silencieuse', 'Cycle interrompu ou code erreur'], observations: ['Eau encore dans le tambour', 'Arrêt avant ou pendant l’essorage', 'Bourdonnement, clic ou silence', 'Code erreur et référence du modèle'], safeChecks: ['Arrêter et débrancher à sec si possible', 'Lire la notice pour la vidange d’urgence prévue par le fabricant', 'Observer le tuyau extérieur sans déplacer l’appareil', 'Préparer une bassine seulement si la notice prévoit un accès sûr'], safeActions: ['Nettoyer un filtre uniquement si la notice le prévoit et si l’appareil est hors tension, froid et stable', 'Photographier le code erreur et la référence'], stopConditions: ['Eau proche d’électricité', 'Tuyau ou filtre qui résiste', 'Besoin de coucher ou déplacer l’appareil', 'Odeur de brûlé, fumée ou câblage à ouvrir'], whenToCallPro: 'Un réparateur est recommandé si la vidange d’urgence n’est pas clairement prévue, si la pompe reste silencieuse ou si l’appareil doit être démonté.', faq: [{ question: 'Pourquoi y a-t-il encore de l’eau dans le tambour ?', answer: 'Un cycle interrompu, une évacuation ralentie ou un problème de pompe sont possibles. Le bruit, le code erreur et le moment d’arrêt aident à orienter.' }, { question: 'Puis-je ouvrir le filtre de vidange ?', answer: 'Seulement si la notice décrit cette opération et que l’appareil est hors tension, stable et que l’eau peut être contenue. Sinon, arrêtez-vous.' }], related: ['machine-a-laver-qui-fuit', 'lave-linge-nessore-plus', 'eau-au-fond-du-lave-vaisselle'],
  },
  {
    slug: 'lave-vaisselle-ne-vidange-plus', category: 'Électroménager', categorySlug: 'electromenager', title: 'Lave-vaisselle qui ne vidange plus : que vérifier ?', metaTitle: 'Lave-vaisselle ne vidange plus : vérifications | NALVIUM', metaDescription: 'Lave-vaisselle qui ne vidange plus : distinguez eau résiduelle, filtre, tuyau, pompe et code erreur sans démontage électrique.', intro: 'Un peu d’eau peut rester selon la conception de l’appareil, mais une quantité anormale après le cycle mérite une observation structurée.', quickAnswer: 'Comparez la quantité d’eau avec la notice, regardez le filtre et le tuyau accessibles, puis écoutez si la pompe tente de démarrer. Débranchez avant toute manipulation prévue par la notice.', causes: ['Eau résiduelle normale selon le modèle', 'Filtre accessible chargé de résidus', 'Tuyau visible plié ou évacuation ralentie', 'Pompe bruyante, silencieuse ou code erreur'], observations: ['Petite quantité au fond ou cuve fortement remplie', 'Filtre et zone de bonde visibles', 'Bruit de pompe pendant la vidange', 'Code erreur et moment d’apparition'], safeChecks: ['Arrêter le programme et débrancher à sec si possible', 'Retirer seulement les résidus visibles avec des gants', 'Observer le tuyau sans tirer sur l’appareil', 'Consulter la notice du modèle'], safeActions: ['Nettoyer le filtre uniquement si son accès est prévu par la notice', 'Photographier la cuve, le filtre et le code erreur'], stopConditions: ['Eau proche d’une prise', 'Filtre bloqué ou pièce cassée', 'Odeur de brûlé, fumée ou bruit inquiétant', 'Besoin d’ouvrir un panneau ou de toucher au câblage'], whenToCallPro: 'Un réparateur est préférable si l’eau reste en quantité anormale après les contrôles prévus, si la pompe est inaccessible ou si un risque électrique apparaît.', faq: [{ question: 'Est-il normal d’avoir un peu d’eau au fond du lave-vaisselle ?', answer: 'Cela dépend de la conception du modèle. Comparez avec la notice et distinguez un petit niveau stable d’une cuve qui ne se vide plus.' }, { question: 'Puis-je nettoyer le filtre ?', answer: 'Oui uniquement si le filtre est prévu pour être retiré par l’utilisateur, avec l’appareil arrêté et hors tension. Ne forcez pas.' }], related: ['eau-au-fond-du-lave-vaisselle', 'lave-vaisselle-ne-se-remplit-plus'],
  },
  {
    slug: 'eau-au-fond-du-lave-vaisselle', category: 'Électroménager', categorySlug: 'electromenager', title: 'Eau au fond du lave-vaisselle : normale ou anormale ?', metaTitle: 'Eau au fond du lave-vaisselle : que vérifier ? | NALVIUM', metaDescription: 'Eau au fond du lave-vaisselle : mesurez le niveau, observez le filtre et distinguez eau résiduelle et vidange incomplète.', intro: 'Une petite quantité peut être liée au fonctionnement du modèle, tandis qu’une cuve remplie après le cycle indique un symptôme à observer. La notice reste la référence du modèle.', quickAnswer: 'Regardez le niveau après un cycle terminé, l’état du filtre et la présence d’un code erreur. Si l’eau est abondante, sent mauvais ou reste en contact avec l’électricité, arrêtez-vous.', causes: ['Eau résiduelle prévue par l’appareil', 'Filtre ou zone de bonde encombré', 'Tuyau visible plié', 'Vidange incomplète liée à la pompe ou au programme'], observations: ['Petite pellicule ou quantité qui couvre la cuve', 'Eau claire ou chargée de résidus', 'Odeur, bruit de pompe ou code erreur', 'Le phénomène survient après chaque cycle ou une seule fois'], safeChecks: ['Éteindre et débrancher à sec si possible', 'Retirer seulement les résidus visibles', 'Observer le filtre sans outil', 'Consulter la notice avant de retirer une pièce'], safeActions: ['Nettoyer le filtre si l’opération est explicitement prévue', 'Photographier le niveau et la référence de l’appareil'], stopConditions: ['Cuve fortement remplie ou eau potentiellement contaminée', 'Eau proche d’une prise', 'Filtre ou pièce qui résiste', 'Besoin de démonter la pompe ou un panneau'], whenToCallPro: 'Demandez un réparateur si la quantité augmente, si le filtre accessible est propre mais que l’eau reste, ou si la vidange nécessite une intervention interne.', faq: [{ question: 'Quelle quantité d’eau est normale ?', answer: 'Il n’existe pas une quantité universelle pour tous les modèles. La notice et la comparaison avec le fonctionnement habituel sont les meilleurs repères.' }, { question: 'Pourquoi l’eau reste-t-elle après le cycle ?', answer: 'Un filtre, un tuyau, une pompe ou un cycle interrompu peuvent être en cause parmi d’autres possibilités.' }], related: ['lave-vaisselle-ne-vidange-plus', 'lave-vaisselle-ne-se-remplit-plus'],
  },
  {
    slug: 'four-ne-chauffe-plus', category: 'Électroménager', categorySlug: 'electromenager', title: 'Four qui ne chauffe plus : que vérifier sans ouvrir l’appareil ?', metaTitle: 'Four ne chauffe plus : vérifications sûres | NALVIUM', metaDescription: 'Four qui ne chauffe plus : observez le mode, le voyant, le disjoncteur et le code erreur sans travail sous tension.', intro: 'Un four peut sembler fonctionner tout en ne chauffant pas, ou ne plus démarrer du tout. Les contrôles doivent rester externes et conformes à la notice.', quickAnswer: 'Vérifiez le mode sélectionné, la température demandée, le voyant et un éventuel code erreur. Ne retirez aucun capot et n’intervenez jamais dans un four sous tension.', causes: ['Mode ou température mal sélectionné', 'Cycle ou sécurité de porte non engagé', 'Alimentation ou disjoncteur à faire vérifier', 'Élément chauffant, thermostat ou électronique nécessitant un réparateur'], observations: ['Ventilation, voyant et bruit habituels', 'Chauffe absente en haut, en bas ou dans tous les modes', 'Code erreur ou disjoncteur déclenché', 'Odeur de brûlé, fumée ou chaleur anormale'], safeChecks: ['Arrêter le four et le laisser refroidir', 'Lire la notice du modèle', 'Observer l’affichage et le mode choisi', 'Vérifier le tableau uniquement sans ouvrir ni toucher, et seulement si tout est sec et sûr'], safeActions: ['Photographier le code erreur et la référence', 'Comparer un autre mode uniquement si aucun signe de danger n’est présent'], stopConditions: ['Fumée, odeur de brûlé ou étincelle', 'Disjoncteur qui déclenche à nouveau', 'Capot, câblage ou résistance à toucher', 'Toute intervention sous tension'], whenToCallPro: 'Un réparateur doit intervenir dès qu’un composant, un câblage ou une mesure électrique est en cause. NALVIUM ne guide aucun travail sous tension.', faq: [{ question: 'Puis-je changer la résistance du four ?', answer: 'Pas dans le cadre d’une vérification guidée : cela implique un accès technique et une mise hors tension vérifiée. Demandez un professionnel.' }, { question: 'Pourquoi le four ventile mais ne chauffe pas ?', answer: 'Le ventilateur et le chauffage sont des fonctions distinctes. Plusieurs causes sont possibles ; observez le mode et le code erreur sans ouvrir.' }], related: ['refrigerateur-ne-refroidit-plus'],
  },
  {
    slug: 'refrigerateur-ne-refroidit-plus', category: 'Électroménager', categorySlug: 'electromenager', title: 'Réfrigérateur qui ne refroidit plus : que vérifier ?', metaTitle: 'Réfrigérateur ne refroidit plus : vérifications | NALVIUM', metaDescription: 'Réfrigérateur qui ne refroidit plus : observez température, bruit, givre et ventilation sans toucher au circuit frigorifique.', intro: 'Une température trop élevée peut venir du réglage, de l’air qui circule mal ou d’une panne. Protégez les aliments et observez l’extérieur avant toute autre action.', quickAnswer: 'Vérifiez le réglage, la fermeture de la porte, la ventilation et les bruits habituels. Ne percez pas la glace, ne manipulez pas le circuit frigorifique et débranchez uniquement si la zone est sèche.', causes: ['Réglage ou mode particulier', 'Porte, joint ou circulation d’air gênée', 'Givre ou ventilation anormale', 'Compresseur ou circuit frigorifique nécessitant un professionnel'], observations: ['Température approximative et évolution', 'Bruit du compresseur ou silence inhabituel', 'Givre localisé ou paroi très chaude', 'Joint, porte et espace de ventilation'], safeChecks: ['Vérifier la fermeture de la porte', 'Dégager les aérations extérieures sans démonter', 'Lire la notice du modèle', 'Photographier la référence et les voyants'], safeActions: ['Débrancher seulement si la prise et le sol sont secs et si la notice le prévoit', 'Transférer les aliments sensibles si cela peut être fait sans risque'], stopConditions: ['Odeur de brûlé, fumée ou choc électrique', 'Câblage ou compresseur à ouvrir', 'Circuit frigorifique à toucher', 'Eau proche d’une prise'], whenToCallPro: 'Un réparateur est recommandé si le froid ne revient pas après les contrôles externes, si le circuit ou le compresseur est en cause, ou si la sécurité alimentaire est engagée.', faq: [{ question: 'Puis-je gratter le givre avec un objet ?', answer: 'Non. Ne percez pas les parois et n’utilisez pas d’objet pointu ; suivez uniquement la procédure de la notice.' }, { question: 'Pourquoi le réfrigérateur fait-il du bruit mais ne refroidit plus ?', answer: 'Le bruit peut venir de plusieurs fonctions. Notez son type, la température et le givre sans ouvrir le circuit frigorifique.' }], related: ['four-ne-chauffe-plus'],
  },
  {
    slug: 'lave-linge-nessore-plus', category: 'Électroménager', categorySlug: 'electromenager', title: 'Lave-linge qui n’essore plus : que vérifier ?', metaTitle: 'Lave-linge n’essore plus : vérifications sûres | NALVIUM', metaDescription: 'Lave-linge qui n’essore plus : distinguez eau restante, charge déséquilibrée, pompe silencieuse et code erreur sans démontage.', intro: 'Un tambour qui ne part pas en essorage peut être lié à de l’eau restante, à une charge déséquilibrée ou à un problème signalé par l’appareil.', quickAnswer: 'Notez si le tambour contient encore de l’eau, si la machine s’arrête avant l’essorage, si la pompe fait du bruit et si un code apparaît. Débranchez à sec avant toute vérification prévue par la notice.', causes: ['Vidange incomplète empêchant l’essorage', 'Charge déséquilibrée ou programme choisi', 'Tuyau visible plié ou filtre accessible encombré', 'Pompe, moteur ou sécurité nécessitant un réparateur'], observations: ['Eau dans le tambour', 'Arrêt avant ou pendant l’essorage', 'Bruit de pompe, clic ou silence', 'Code erreur et type de charge'], safeChecks: ['Arrêter le programme et débrancher si la zone est sèche', 'Consulter la notice du code et du filtre', 'Observer le tuyau extérieur sans déplacer l’appareil', 'Répartir la charge seulement si le tambour est accessible et sec'], safeActions: ['Lancer uniquement un programme prévu par la notice, sans signe de fuite ou de danger', 'Photographier le code erreur et la référence'], stopConditions: ['Eau proche d’électricité', 'Odeur de brûlé, fumée ou choc', 'Appareil à coucher ou déplacer', 'Capot ou sécurité à ouvrir'], whenToCallPro: 'Un réparateur est préférable si l’appareil ne vidange pas, si la pompe reste silencieuse ou si l’essorage demande une intervention interne.', faq: [{ question: 'Pourquoi le lave-linge s’arrête-t-il avant l’essorage ?', answer: 'De l’eau restante, une charge déséquilibrée, un programme ou un code erreur peuvent l’expliquer parmi d’autres possibilités.' }, { question: 'Puis-je relancer un essorage ?', answer: 'Seulement si la machine est stable, sans eau dangereuse ni fuite, et si la notice ne signale pas d’erreur. Sinon, arrêtez-vous.' }], related: ['lave-linge-ne-vidange-plus', 'machine-a-laver-qui-fuit'],
  },
  {
    slug: 'lave-vaisselle-ne-se-remplit-plus', category: 'Électroménager', categorySlug: 'electromenager', title: 'Lave-vaisselle qui ne se remplit plus d’eau : que vérifier ?', metaTitle: 'Lave-vaisselle ne se remplit plus d’eau | NALVIUM', metaDescription: 'Lave-vaisselle qui ne se remplit plus : observez arrivée d’eau, porte, bruit et code erreur sans démonter ni toucher à l’électricité.', intro: 'Un lave-vaisselle qui démarre sans prendre d’eau peut signaler une porte, une arrivée d’eau, un filtre ou un système interne à contrôler.', quickAnswer: 'Vérifiez que la porte ferme, que le programme démarre et qu’aucun tuyau visible n’est plié. Ne démontez pas l’arrivée et débranchez avant toute opération prévue par la notice.', causes: ['Porte ou sécurité de fermeture non validée', 'Arrivée d’eau fermée ou tuyau visible plié', 'Filtre d’arrivée accessible selon le modèle', 'Électrovanne, capteur ou commande nécessitant un réparateur'], observations: ['Bruit de remplissage ou silence', 'Code erreur et moment d’arrêt', 'Porte qui ferme normalement', 'Tuyau extérieur accessible et état sec'], safeChecks: ['Arrêter et débrancher à sec si possible', 'Lire la notice du modèle', 'Observer le tuyau sans tirer ni déplacer l’appareil', 'Vérifier visuellement la fermeture de la porte'], safeActions: ['Nettoyer un filtre uniquement si la notice prévoit son accès', 'Photographier le code et la référence de l’appareil'], stopConditions: ['Eau proche d’une prise', 'Tuyau ou raccord qui fuit', 'Odeur de brûlé, fumée ou bruit inquiétant', 'Besoin d’ouvrir un panneau ou de forcer une arrivée'], whenToCallPro: 'Un réparateur est recommandé si l’appareil reste silencieux, si l’arrivée doit être démontée ou si un composant interne est suspecté.', faq: [{ question: 'Pourquoi le lave-vaisselle démarre-t-il sans prendre d’eau ?', answer: 'La porte, l’arrivée, un tuyau visible, un code ou un composant interne peuvent être en cause. Notez le moment précis où le programme s’arrête.' }, { question: 'Puis-je démonter le tuyau d’arrivée ?', answer: 'Non comme première vérification. Observez-le extérieurement et suivez la notice ; arrêtez-vous en cas de fuite ou de résistance.' }], related: ['lave-vaisselle-ne-vidange-plus', 'eau-au-fond-du-lave-vaisselle'],
  },
];

export const guideBySlug = Object.fromEntries(guides.map((guide) => [guide.slug, guide])) as Record<string, Guide>;
export const categories = [
  { slug: 'plomberie', label: 'Plomberie', description: 'Fuites, évacuations, robinetterie et WC : comprendre le symptôme avant d’agir.' },
  { slug: 'electromenager', label: 'Électroménager', description: 'Lave-linge, lave-vaisselle, four et réfrigérateur : observer sans démontage risqué.' },
  { slug: 'bricolage', label: 'Bricolage', description: 'Petites fixations et objets du quotidien, avec une limite claire quand le risque change.' },
  { slug: 'electricite', label: 'Électricité', description: 'Identifier et mettre en sécurité. Aucune intervention sur conducteurs ou tableau.' },
];

export const cities = {
  nice: { name: 'Nice', department: 'Alpes-Maritimes', intro: 'Si vous cherchez un plombier à Nice, NALVIUM peut d’abord vous aider à identifier ce qui se passe chez vous, gratuitement.', problems: ['Fuite sous évier', 'Robinet qui goutte', 'Chasse d’eau qui coule', 'Évier bouché'] },
  lyon: { name: 'Lyon', department: 'Rhône', intro: 'Une recherche de plombier à Lyon commence parfois par une question plus simple : quel est exactement le problème à montrer ?', problems: ['Fuite sous évier', 'Évier bouché', 'Robinet qui goutte', 'Chasse d’eau qui coule'] },
};

export const storeLinks = { appStoreUrl: '', googlePlayUrl: '' };

export const photoAssets = {
  leakUnderSink: { src: '/images/nalvium/problems/fuite-sous-evier.webp', alt: 'Intérieur d’un meuble sous évier avec siphon blanc, gouttes et flaque d’eau visibles' },
  plumbingMosaic: { src: '/images/nalvium/problems/fuite-sous-evier.webp', alt: 'Intérieur d’un meuble sous évier avec siphon blanc, gouttes et flaque d’eau visibles' },
  cloggedSink: { src: '/images/nalvium/problems/evier-bouche.jpg', alt: 'Bonde d’un évier domestique avec de l’eau qui s’évacue lentement' },
  toilet: { src: '/images/nalvium/appliances/wc.jpg', alt: 'WC moderne clairement visible dans une salle de bains domestique' },
  washingMachine: { src: '/images/nalvium/problems/lave-linge.jpg', alt: 'Lave-linge domestique clairement visible dans une cuisine' },
  washingMachineDrain: { src: '/images/nalvium/problems/lave-linge-vidange.jpg', alt: 'Tambour intérieur d’un lave-linge domestique' },
  dishwasher: { src: '/images/nalvium/appliances/lave-vaisselle.jpg', alt: 'Intérieur d’un lave-vaisselle domestique ouvert avec sa vaisselle visible' },
  leakingFaucet: { src: '/images/nalvium/problems/robinet-goutte.jpg', alt: 'Robinet domestique avec une goutte d’eau visible' },
  stepProblem: { src: '/images/nalvium/problems/probleme-domestique.jpg', alt: 'Robinet domestique qui goutte, problème clairement identifiable' },
  oven: { src: '/images/nalvium/appliances/four.jpg', alt: 'Four encastré clairement identifiable dans une cuisine domestique' },
  refrigerator: { src: '/images/nalvium/appliances/refrigerateur.jpg', alt: 'Réfrigérateur domestique clairement identifiable dans une cuisine' },
  wallMounting: { src: '/images/nalvium/problems/outils-bricolage.jpg', alt: 'Outils domestiques pour une petite intervention de bricolage' },
  electricalOutlet: { src: '/images/nalvium/safety/prise-electrique.jpg', alt: 'Prise et fiche électriques domestiques, sans conducteurs exposés' },
  waterHeater: { src: '/images/nalvium/pro/chauffe-eau.jpg', alt: 'Équipement de chauffe-eau domestique et sa tuyauterie' },
  houseLaundry: { src: '/images/nalvium/pro/buanderie.jpg', alt: 'Buanderie domestique contemporaine avec lave-linge clairement visible' },
} as const;

export const categoryImages = {
  plomberie: photoAssets.leakUnderSink,
  electromenager: photoAssets.washingMachine,
  bricolage: photoAssets.wallMounting,
  electricite: photoAssets.electricalOutlet,
} as const;
