import Link from 'next/link';
import { ButtonLink, CameraScene, Icon, ObservationDemo, ProblemGallery, SafetyStrip, StoreBadges } from './components';

export default function Home() { return <main>
  <section className="hero-v3"><div className="hero-v3-copy"><span className="eyebrow">VOUS AVEZ UN PROBLÈME CHEZ VOUS.</span><h1>Montrez-nous<br /><em>le problème.</em></h1><p className="product-line">NALVIUM regarde avec vous.</p><p>Une photo. Une observation claire. Une prochaine action. Et si vous devez appeler quelqu’un, vous savez déjà pourquoi.</p><div className="actions"><ButtonLink href="/comment-ca-marche">Montrer mon problème</ButtonLink></div><StoreBadges /><div className="hero-v3-proof"><span className="proof-mark">N</span><span>Vous gardez le contrôle.<br /><b>NALVIUM observe avant de conclure.</b></span></div></div><CameraScene priority /></section>
  <section className="signature-section"><div className="signature-copy"><span className="eyebrow">UNE AUTRE FAÇON DE COMMENCER</span><h2>NALVIUM ne vous demande pas de connaître le nom de la panne.</h2><p>Vous montrez. Il observe. Vous décidez avec plus d’informations.</p></div><div className="signature-steps"><div><b>01</b><strong>MONTRER</strong><span>Une photo ou une courte vidéo.</span></div><div><b>02</b><strong>CIBLER</strong><span>NALVIUM attire l’attention sur ce qui compte.</span></div><div><b>03</b><strong>AGIR</strong><span>Une seule action sûre à la fois.</span></div><div><b>04</b><strong>DÉCIDER</strong><span>Réglé, à vérifier, ou professionnel.</span></div></div></section>
  <ObservationDemo />
  <section className="gallery-section"><div className="gallery-heading"><span className="eyebrow">CE QUE LES GENS MONTRENT À NALVIUM</span><h2>Pas des catégories techniques.<br /><em>Des problèmes tels qu’ils apparaissent chez vous.</em></h2></div><ProblemGallery /></section>
  <section className="decision-section"><div className="decision-heading"><span className="eyebrow">LA BONNE PROCHAINE DÉCISION</span><h2>NALVIUM ne pousse pas vers une intervention.<br /><em>Il pousse vers la bonne prochaine décision.</em></h2></div><div className="decision-paths"><div className="decision-path"><span className="path-label">LE PROBLÈME RESTE SIMPLE</span><h3>Continuez avec NALVIUM.</h3><p>Une action claire, une vérification, puis une nouvelle observation si nécessaire.</p><div className="action-slip"><small>ACTION SÛRE</small><strong>Fermez l’arrivée d’eau.</strong><span>Puis montrez-moi ce qui change.</span></div></div><div className="path-connector">→</div><div className="decision-path"><span className="path-label pro">IL FAUT PASSER LA MAIN</span><h3>Le professionnel reçoit du contexte.</h3><p>Seulement ce que vous choisissez de transmettre, après votre consentement.</p><div className="case-file"><small>DOSSIER NALVIUM</small><h4>Fuite sous évier</h4><div className="case-line"><span>Observé</span><b>Eau près du siphon</b></div><div className="case-line"><span>Déjà vérifié</span><b>Arrivée fermée</b></div><div className="case-line"><span>Photos</span><b>2</b></div><Link className="button" href="/professionnels">Trouver un professionnel <Icon name="arrow" /></Link></div></div></div></section>
  <SafetyStrip />
  <section className="house-memory"><div><span className="eyebrow">MA MAISON</span><h2>Et demain,<br /><em>NALVIUM se souvient.</em></h2><p>Votre maison devient plus facile à comprendre au fil du temps. Un carnet technique qui se construit avec ce que vous choisissez de garder.</p><ButtonLink href="/ma-maison" secondary>Découvrir Ma Maison</ButtonLink></div><div className="memory-line"><div className="memory-entry"><time>2026</time><strong>Chauffe-eau</strong><span>Référence enregistrée</span></div><div className="memory-entry"><time>MAI</time><strong>Fuite évier</strong><span>Diagnostic conservé</span></div><div className="memory-entry"><time>AOÛT</time><strong>Lave-linge</strong><span>Notice ajoutée</span></div><div className="memory-entry current"><time>AUJOURD’HUI</time><strong>Ma Maison</strong><span>Tout le contexte au même endroit</span></div></div></section>
  <section className="v3-cta" id="diagnostic"><div><span className="eyebrow">GRATUIT POUR LES PARTICULIERS</span><h2>Un problème à la maison ?<br /><em>Montrez-le à NALVIUM.</em></h2></div><div className="cta-side"><ButtonLink href="/comment-ca-marche">Montrer mon problème</ButtonLink><StoreBadges /></div></section>
</main> }
