import { LegalPage, LegalSection } from '../legal';

export const metadata = {
  title: 'Politique de confidentialité',
  description: 'Comment NALVIUM et 3E Technology Ltd traitent les informations liées au service.',
  alternates: { canonical: '/confidentialite' },
};

export default function Confidentialite() {
  return <LegalPage eyebrow="NALVIUM · DONNÉES PERSONNELLES" title="Politique de confidentialité" intro="Cette politique explique les catégories d’informations que NALVIUM peut traiter, pourquoi elles peuvent l’être et comment exercer vos droits.">
    <LegalSection title="Responsable du traitement"><p>Le responsable du traitement est <strong>3E Technology Ltd</strong>.</p><p>Contact : <a href="mailto:contact@nalvium.com">contact@nalvium.com</a>.</p></LegalSection>
    <LegalSection title="Données traitées dans l’application"><p>Selon les fonctions utilisées, NALVIUM peut traiter une identité d’installation ou de compte, les photos, vidéos, enregistrements audio et transcriptions envoyés, les descriptions de problèmes, les réponses aux questions, les diagnostics structurés, les équipements, notices, factures, garanties, documents, historiques, réparations avant/après, publications ou commentaires communautaires volontaires, signalements, consentements et demandes professionnelles.</p><p>Pour une demande professionnelle, les informations peuvent inclure le prénom, le téléphone, la ville, le code postal, le créneau souhaité, la description, le résumé et les médias choisis. Toutes les fonctions ne collectent pas toutes ces catégories.</p></LegalSection>
    <LegalSection title="Photos et médias du domicile"><p>Les photos et vidéos peuvent montrer involontairement des personnes, documents, adresses, objets personnels, plaques, clés, codes ou autres informations visibles dans le logement. Cadrez uniquement le problème et évitez les éléments inutiles.</p><p>Les médias envoyés pour un diagnostic sont conservés dans un stockage privé côté backend. Les images sont normalisées côté serveur et les métadonnées EXIF non nécessaires ne sont pas conservées dans ce traitement.</p></LegalSection>
    <LegalSection title="Systèmes automatisés et intelligence artificielle"><p>Les informations envoyées pour un diagnostic, notamment les textes et médias nécessaires, peuvent être traitées par des systèmes automatisés ou d’intelligence artificielle afin de produire des observations, hypothèses, questions, vérifications et recommandations de sécurité.</p><p>Le résultat peut être inexact ou incomplet. Il ne constitue pas un diagnostic certain et ne remplace pas un professionnel. Le fournisseur IA est configuré côté serveur ; aucun nom de fournisseur n’est indiqué ici.</p></LegalSection>
    <LegalSection title="Professionnels et consentement"><p>Aucune coordonnée ni aucun média n’est transmis à un professionnel sans sélection et consentement préalable dans le parcours concerné. Cliquer sur une entrée professionnelle ne vaut pas, à lui seul, consentement à une transmission.</p><p>NALVIUM ne garantit ni réseau national, ni disponibilité, ni prix, ni rendez-vous.</p></LegalSection>
    <LegalSection title="Analytics et publicité"><p>Le site public ne contient pas d’outil d’analytics tiers identifié. Les événements techniques prévus dans l’application ne doivent pas contenir de photos, conversations, descriptions libres complètes, téléphone ou adresse précise. Les publicités mobiles sont désactivées par défaut dans la version documentée.</p></LegalSection>
    <LegalSection title="Conservation et sécurité"><p>Les données sont conservées uniquement pour les finalités du service et tant que cela est nécessaire. Les durées précises dépendent de la catégorie de données et doivent être fixées dans la documentation de conservation applicable.</p><p>NALVIUM applique la minimisation, protège les médias privés et prévoit des fonctions de suppression. Consultez <a href="/securite">la page Sécurité</a> pour les situations à risque.</p></LegalSection>
    <LegalSection title="Vos droits"><p>Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, l’opposition, la portabilité lorsque celle-ci est applicable, ainsi que le retrait d’un consentement lorsque le traitement repose sur celui-ci.</p><p>Écrivez à <a href="mailto:contact@nalvium.com">contact@nalvium.com</a>. Aucun délégué à la protection des données n’est présenté sur cette page.</p></LegalSection>
  </LegalPage>;
}
