import type { Metadata } from 'next';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { Breadcrumbs, ButtonLink, FAQ, PageHero, PhotoBand, RelatedGuides, SafetyStop, SectionHeader, SiteCta } from '../../../components';
import { guideBySlug, photoAssets } from '../../../data';

type LocalProblem = { title: string; metaTitle: string; description: string; intro: string; image: { src: string; alt: string }; observations: string[]; checks: string[]; causes: string[]; stop: string[]; guide?: string; related: string[]; faq: { question: string; answer: string }[] };
const baseFaq = (question: string, answer: string) => [{ question, answer }, { question: 'NALVIUM remplace-t-il un plombier ?', answer: 'Non. NALVIUM aide à montrer le problème, comprendre des causes probables et effectuer uniquement des vérifications sûres avant de décider si un professionnel est nécessaire.' }];
const localProblems: Record<string, LocalProblem> = {
  'fuite-eau': { title: 'Fuite d’eau à Lyon : que vérifier avant de faire intervenir un plombier ?', metaTitle: 'Fuite d’eau à Lyon : que vérifier avant un plombier ?', description: 'Fuite d’eau à Lyon : observez l’origine, sécurisez la situation sans danger et sachez quand arrêter avant de faire intervenir un plombier.', intro: 'Une fuite sous évier, sur un robinet, un flexible, un raccord visible, un WC ou un chauffe-eau ne se vérifie pas de la même manière. Commencez par ce qui est visible.', image: photoAssets.leakUnderSink, observations: ['Le point où l’eau apparaît en premier', 'Si la fuite est permanente ou seulement pendant l’utilisation', 'L’équipement concerné', 'La présence d’eau près d’une prise ou d’un appareil électrique'], checks: ['Placer un récipient stable sous la zone si cela reste possible sans danger', 'Sécher uniquement l’extérieur d’un raccord accessible et observer où l’humidité revient', 'Fermer l’arrivée d’eau si elle est identifiable et tourne sans forcer', 'Photographier la zone avant de déplacer quoi que ce soit'], causes: ['Un raccord ou un joint visible', 'Une fuite située plus haut', 'Une évacuation qui refoule lorsque l’eau coule', 'Une fuite non localisée nécessitant un examen professionnel'], stop: ['Fuite importante ou impossible à contenir', 'Eau proche d’une prise, d’une multiprise ou d’un appareil électrique', 'Raccord corrodé, fissuré ou qui résiste', 'Origine incertaine'], guide: 'fuite-sous-evier', related: ['fuite-sous-evier', 'robinet-qui-goutte', 'chasse-eau-qui-coule'], faq: baseFaq('Faut-il couper l’eau immédiatement ?', 'Seulement si la commande est clairement accessible et peut être fermée sans effort. Si l’eau approche une installation électrique, éloignez-vous et demandez une aide adaptée.') },
  'wc-bouche': { title: 'WC bouché à Lyon : que faire avant d’appeler un plombier ?', metaTitle: 'WC bouché à Lyon : que faire avant un plombier ?', description: 'WC bouché à Lyon : distinguez eau qui monte, évacuation lente et bouchon local avec des vérifications prudentes, sans mélange chimique.', intro: 'Le niveau d’eau, la vitesse d’évacuation et l’état des autres équipements donnent des indices utiles. Le premier objectif est d’éviter le débordement.', image: photoAssets.toilet, observations: ['Si l’eau monte ou redescend lentement', 'Si le problème apparaît après la chasse', 'Si un autre équipement est touché', 'La présence éventuelle d’un produit déjà versé'], checks: ['Ne pas rajouter d’eau si le niveau monte', 'Fermer l’arrivée du WC si elle est accessible sans forcer', 'Protéger le sol et observer si le bouchon reste local', 'Utiliser une ventouse uniquement sans produit chimique'], causes: ['Bouchon local dans la cuvette ou la sortie', 'Évacuation ralentie', 'Obstruction plus loin si plusieurs équipements sont touchés', 'Refoulement nécessitant un professionnel'], stop: ['Eau qui déborde ou refoulement important', 'Plusieurs évacuations touchées', 'Produit chimique présent ou inconnu', 'Besoin de démonter ou forcer'], related: ['chasse-eau-qui-coule', 'evier-bouche', 'fuite-sous-evier'], faq: baseFaq('Que faire si l’eau monte dans la cuvette ?', 'N’ajoutez pas d’eau, fermez l’arrivée si elle est accessible sans forcer et arrêtez-vous si le niveau continue de monter.') },
  'evier-bouche': { title: 'Évier bouché à Lyon : les vérifications simples avant une intervention', metaTitle: 'Évier bouché à Lyon : vérifications simples avant intervention', description: 'Évier bouché à Lyon : observez l’eau stagnante, le siphon et les autres évacuations sans mélanger de produits.', intro: 'Une eau stagnante, une évacuation lente ou une mauvaise odeur peuvent venir de la bonde, du siphon ou d’une canalisation plus loin.', image: photoAssets.cloggedSink, observations: ['Niveau et vitesse d’évacuation', 'Mauvaise odeur, glouglou ou refoulement', 'Présence d’un produit déboucheur', 'Nombre d’équipements touchés'], checks: ['Limiter l’eau ajoutée et protéger le meuble', 'Retirer uniquement les débris visibles avec des gants adaptés', 'Observer le dessous de l’évier sans démonter', 'Utiliser une ventouse seulement sans produit chimique'], causes: ['Débris près de la bonde', 'Siphon encombré', 'Bouchon plus loin', 'Problème général si plusieurs équipements sont touchés'], stop: ['Produit chimique déjà présent ou inconnu', 'Fuite du siphon ou raccord qui résiste', 'Refoulement important', 'Plusieurs évacuations touchées'], guide: 'evier-bouche', related: ['fuite-sous-evier', 'robinet-qui-goutte'], faq: baseFaq('Puis-je démonter le siphon ?', 'Pas automatiquement. Si un produit chimique est présent, si une fuite existe ou si le raccord résiste, ne démontez pas.') },
  'canalisation-bouchee': { title: 'Canalisation bouchée à Lyon : comment savoir si le problème est local ou général ?', metaTitle: 'Canalisation bouchée à Lyon : local ou général ?', description: 'Canalisation bouchée à Lyon : comparez un seul équipement, plusieurs évacuations, les refoulements et les bruits avant de décider.', intro: 'La différence entre un seul équipement bouché et plusieurs évacuations touchées change la prudence à adopter. Observez le réseau sans prétendre effectuer un débouchage professionnel.', image: photoAssets.cloggedSink, observations: ['Un seul équipement ou plusieurs concernés', 'Refoulement dans un évier, une douche ou un WC', 'Bruits de glouglou après un autre équipement', 'Évolution rapide ou blocage récurrent'], checks: ['Éviter d’ajouter beaucoup d’eau pour tester', 'Noter les équipements touchés et dans quel ordre', 'Photographier un refoulement sans toucher l’eau', 'Limiter les essais si l’eau remonte ailleurs'], causes: ['Bouchon local', 'Obstruction plus loin dans une branche', 'Réseau commun touché', 'Refoulement nécessitant une intervention'], stop: ['Refoulement d’eau usée', 'Plusieurs équipements touchés', 'Débordement ou risque sanitaire', 'Produit chimique présent ou inconnu'], related: ['evier-bouche', 'fuite-sous-evier'], faq: baseFaq('Comment distinguer un problème local d’un problème général ?', 'Un seul équipement touché oriente vers un problème local, sans le prouver. Plusieurs évacuations lentes, bruyantes ou en refoulement indiquent qu’il faut arrêter les essais et demander un professionnel.') },
  'chasse-eau': { title: 'Chasse d’eau qui coule à Lyon : identifier la cause avant d’appeler un plombier', metaTitle: 'Chasse d’eau qui coule à Lyon : identifier la cause', description: 'Chasse d’eau qui coule à Lyon : observez le flotteur, le mécanisme, le joint et le remplissage continu avant d’appeler un plombier.', intro: 'Un filet d’eau dans la cuvette, un remplissage continu ou une fuite autour du réservoir ne conduisent pas aux mêmes vérifications.', image: photoAssets.toilet, observations: ['Filet d’eau continu dans la cuvette', 'Bruit de remplissage après la chasse', 'Position visible du flotteur ou du bouton', 'Traces d’eau autour du réservoir'], checks: ['Fermer le petit robinet d’arrivée s’il tourne normalement', 'Observer le mécanisme sans débrancher ni forcer', 'Vérifier si le bouton revient correctement', 'Photographier le mécanisme visible'], causes: ['Flotteur mal positionné ou qui ne ferme plus', 'Mécanisme usé', 'Joint qui n’assure plus l’étanchéité', 'Fuite extérieure du réservoir'], stop: ['Robinet d’arrêt bloqué', 'Réservoir fissuré ou fuite extérieure', 'Besoin de forcer ou démonter', 'Eau proche d’un équipement électrique'], guide: 'chasse-eau-qui-coule', related: ['fuite-sous-evier', 'evier-bouche'], faq: baseFaq('Puis-je régler le flotteur ?', 'Seulement si un réglage est clairement accessible et prévu pour cela. Ne forcez pas une pièce et arrêtez si vous n’identifiez pas le mécanisme.') },
  'chauffe-eau': { title: 'Problème de chauffe-eau à Lyon : que vérifier avant une intervention ?', metaTitle: 'Problème de chauffe-eau à Lyon : que vérifier ?', description: 'Chauffe-eau à Lyon : distinguez absence d’eau chaude, fuite visible, bruit ou groupe de sécurité sans ouvrir l’électricité ni intervenir sur le gaz.', intro: 'Un chauffe-eau combine eau, électricité ou parfois gaz. NALVIUM aide uniquement à observer l’extérieur et à reconnaître le moment où il faut s’arrêter.', image: photoAssets.waterHeater, observations: ['Plus d’eau chaude ou température inhabituelle', 'Fuite visible autour de la cuve ou du groupe de sécurité', 'Bruit inhabituel', 'Voyant, disjoncteur ou alimentation apparemment anormale'], checks: ['Observer l’extérieur sans retirer de capot', 'Repérer une fuite visible et protéger le sol si cela reste sûr', 'Noter si le problème touche toute l’eau chaude ou un seul point', 'Photographier les éléments extérieurs et références visibles'], causes: ['Groupe de sécurité qui goutte', 'Alimentation ou réglage à contrôler', 'Résistance, thermostat ou cuve à faire examiner', 'Installation gaz ou électrique nécessitant un professionnel'], stop: ['Eau près d’une installation électrique', 'Odeur de gaz, fumée, chaleur ou bruit inquiétant', 'Capot électrique ou câblage à ouvrir', 'Toute intervention sur le gaz ou fuite importante'], related: ['fuite-sous-evier'], faq: baseFaq('Puis-je ouvrir le capot électrique ?', 'Non. NALVIUM ne guide pas l’ouverture d’une partie électrique ni une manipulation sous tension.') },
  'recherche-fuite': { title: 'Recherche de fuite à Lyon : comment orienter les premières vérifications ?', metaTitle: 'Recherche de fuite à Lyon : premières vérifications', description: 'Recherche de fuite à Lyon : documentez une trace d’humidité, distinguez fuite visible et origine incertaine et sachez quand arrêter.', intro: 'Une trace humide ne montre pas toujours l’endroit où l’eau entre. Commencez par suivre son évolution sans ouvrir un mur, déplacer une installation ou toucher à l’électricité.', image: photoAssets.leakUnderSink, observations: ['La taille et l’évolution de la trace', 'Si elle apparaît après l’utilisation d’un équipement', 'Les zones situées au-dessus ou à proximité', 'La présence d’électricité ou d’un appareil dans la zone'], checks: ['Photographier la trace et noter l’heure de l’observation', 'Sécher seulement une surface accessible pour voir si l’humidité revient', 'Observer les équipements voisins sans démonter', 'Éloigner ce qui peut l’être uniquement si la zone reste sèche et sûre'], causes: ['Fuite visible sur un raccord voisin', 'Eau provenant d’un point situé plus haut', 'Condensation ou infiltration à distinguer', 'Origine non localisée nécessitant un professionnel'], stop: ['Trace qui s’étend rapidement', 'Eau proche d’une installation électrique', 'Besoin d’ouvrir un mur, un plafond ou un capot', 'Origine impossible à suivre sans prise de risque'], related: ['fuite-sous-evier', 'robinet-qui-goutte'], faq: baseFaq('Une trace d’humidité indique-t-elle l’origine de la fuite ?', 'Non. Elle indique une zone à observer, mais l’eau peut venir d’un point différent, parfois situé plus haut ou derrière une paroi.') },
  'robinet-qui-fuit': { title: 'Robinet qui fuit à Lyon : que vérifier avant une intervention ?', metaTitle: 'Robinet qui fuit à Lyon : premières vérifications', description: 'Robinet qui fuit à Lyon : localisez les gouttes, observez le bec, la base et les raccords sans forcer avant de décider de la suite.', intro: 'Un robinet peut goutter par le bec, à sa base ou sur un raccord. Le point visible et le moment où la goutte apparaît sont les premières informations utiles.', image: photoAssets.leakingFaucet, observations: ['L’endroit précis des gouttes', 'Si elles apparaissent robinet ouvert, fermé ou dans les deux cas', 'L’état visible de la base, des flexibles et raccords', 'La présence d’eau dans le meuble'], checks: ['Sécher les surfaces visibles et observer le premier point humide', 'Ouvrir puis fermer doucement sans forcer la poignée', 'Photographier le bec, la base et les raccords', 'Fermer l’eau si la fuite augmente et si l’accès est sûr'], causes: ['Joint ou mécanisme interne usé', 'Flexible ou raccord humide', 'Fuite à la base du robinet', 'Dépôt autour de l’aérateur'], stop: ['Fuite importante', 'Raccord corrodé ou déformé', 'Eau proche d’une prise', 'Poignée bloquée ou besoin de forcer'], guide: 'robinet-qui-goutte', related: ['fuite-sous-evier'], faq: baseFaq('Que faire si le robinet goutte même fermé ?', 'Observez si la goutte vient du bec, de la base ou d’un raccord. Ne démontez pas le mécanisme si vous ne l’identifiez pas clairement.') },
  'ballon-eau-chaude': { title: 'Ballon d’eau chaude à Lyon : que vérifier avant d’appeler ?', metaTitle: 'Ballon d’eau chaude à Lyon : que vérifier ?', description: 'Ballon d’eau chaude à Lyon : observez l’absence d’eau chaude, une fuite ou un bruit sans ouvrir la partie électrique ni intervenir sur le gaz.', intro: 'Le terme ballon d’eau chaude recouvre plusieurs équipements. NALVIUM aide à décrire les signes visibles, sans guider une intervention sous tension ou sur le gaz.', image: photoAssets.waterHeater, observations: ['Plus d’eau chaude sur tous les points ou un seul', 'Fuite visible sous la cuve ou au groupe de sécurité', 'Bruit inhabituel pendant la chauffe', 'Voyant ou alimentation qui semble anormale'], checks: ['Observer l’équipement de l’extérieur', 'Repérer une fuite sans toucher à une zone électrique humide', 'Noter la date d’apparition et l’étendue du problème', 'Photographier les références et raccords visibles'], causes: ['Groupe de sécurité ou raccord visible', 'Réglage ou alimentation à contrôler', 'Composant interne à faire examiner', 'Installation électrique ou gaz nécessitant un professionnel'], stop: ['Eau proche d’une installation électrique', 'Odeur de gaz, fumée ou chaleur anormale', 'Capot ou câblage à ouvrir', 'Fuite importante ou non maîtrisable'], related: ['chauffe-eau', 'fuite-sous-evier'], faq: baseFaq('Un ballon qui ne chauffe plus est-il forcément à remplacer ?', 'Non. Plusieurs causes sont possibles et aucune ne peut être confirmée par une simple observation extérieure. N’ouvrez pas l’appareil.') },
  'degat-des-eaux': { title: 'Dégât des eaux à Lyon : que faire avant une intervention ?', metaTitle: 'Dégât des eaux à Lyon : que faire avant une intervention ?', description: 'Dégât des eaux à Lyon : sécurisez ce qui est visible, documentez les traces et sachez quand arrêter avant de faire intervenir un professionnel.', intro: 'Une arrivée d’eau au plafond, sur un mur ou dans un logement peut avoir une origine locale ou venir d’un autre appartement. La priorité est de limiter le risque et de documenter.', image: photoAssets.leakUnderSink, observations: ['La zone et l’étendue de l’humidité', 'Si l’eau apparaît après l’utilisation d’un équipement', 'La présence d’un logement ou d’un équipement au-dessus', 'La proximité d’une prise, d’un luminaire ou d’un appareil'], checks: ['Photographier les traces et leur évolution', 'Éloigner les objets uniquement si la zone est sûre', 'Prévenir les occupants ou le gardien si un autre logement peut être concerné', 'Limiter l’eau seulement si la commande est accessible sans forcer'], causes: ['Fuite dans le logement', 'Eau provenant d’un étage ou d’une partie commune', 'Évacuation ou équipement voisin', 'Origine non visible nécessitant un professionnel'], stop: ['Eau proche d’électricité ou plafond qui se déforme', 'Fuite importante ou rapide', 'Besoin de toucher à un tableau, un luminaire ou une canalisation cachée', 'Risque structurel ou doute sur la sécurité'], related: ['fuite-eau', 'recherche-fuite'], faq: baseFaq('Que faire si de l’eau apparaît au plafond ?', 'Éloignez-vous de l’électricité humide, documentez la zone sans la toucher et prévenez rapidement les personnes ou professionnels concernés. Ne percez pas et ne démontez pas le plafond.') },
};

const localCrossLinks: Record<string, { label: string; href: string }[]> = {
  'fuite-eau': [{ label: 'Recherche de fuite', href: '/plombier/lyon/recherche-fuite' }, { label: 'Robinet qui fuit', href: '/plombier/lyon/robinet-qui-fuit' }, { label: 'Dégât des eaux', href: '/plombier/lyon/degat-des-eaux' }],
  'recherche-fuite': [{ label: 'Fuite d’eau', href: '/plombier/lyon/fuite-eau' }, { label: 'Robinet qui fuit', href: '/plombier/lyon/robinet-qui-fuit' }, { label: 'Dégât des eaux', href: '/plombier/lyon/degat-des-eaux' }],
  'robinet-qui-fuit': [{ label: 'Fuite d’eau', href: '/plombier/lyon/fuite-eau' }, { label: 'Recherche de fuite', href: '/plombier/lyon/recherche-fuite' }, { label: 'Dégât des eaux', href: '/plombier/lyon/degat-des-eaux' }],
  'degat-des-eaux': [{ label: 'Fuite d’eau', href: '/plombier/lyon/fuite-eau' }, { label: 'Recherche de fuite', href: '/plombier/lyon/recherche-fuite' }, { label: 'Robinet qui fuit', href: '/plombier/lyon/robinet-qui-fuit' }],
  'wc-bouche': [{ label: 'Chasse d’eau', href: '/plombier/lyon/chasse-eau' }, { label: 'Canalisation bouchée', href: '/plombier/lyon/canalisation-bouchee' }],
  'chasse-eau': [{ label: 'WC bouché', href: '/plombier/lyon/wc-bouche' }, { label: 'Canalisation bouchée', href: '/plombier/lyon/canalisation-bouchee' }],
  'canalisation-bouchee': [{ label: 'WC bouché', href: '/plombier/lyon/wc-bouche' }, { label: 'Chasse d’eau', href: '/plombier/lyon/chasse-eau' }, { label: 'Évier bouché', href: '/plombier/lyon/evier-bouche' }],
  'evier-bouche': [{ label: 'Canalisation bouchée', href: '/plombier/lyon/canalisation-bouchee' }],
  'chauffe-eau': [{ label: 'Ballon d’eau chaude', href: '/plombier/lyon/ballon-eau-chaude' }, { label: 'Fuite d’eau', href: '/plombier/lyon/fuite-eau' }],
  'ballon-eau-chaude': [{ label: 'Chauffe-eau', href: '/plombier/lyon/chauffe-eau' }, { label: 'Fuite d’eau', href: '/plombier/lyon/fuite-eau' }],
};

export function generateStaticParams() { return [...Object.keys(localProblems).map(problem => ({ city: 'lyon', problem })), ...['fuite-eau', 'evier-bouche', 'chasse-eau'].map(problem => ({ city: 'nice', problem }))]; }
export async function generateMetadata({ params }: { params: Promise<{ city: string; problem: string }> }): Promise<Metadata> { const { city, problem } = await params; const content = city === 'lyon' ? localProblems[problem] : undefined; if (!content) return {}; const url = `https://nalvium.com/plombier/lyon/${problem}`; return { title: content.metaTitle, description: content.description, alternates: { canonical: url }, openGraph: { title: `${content.metaTitle} | NALVIUM`, description: content.description, url, type: 'article' } }; }

export default async function LocalProblemPage({ params }: { params: Promise<{ city: string; problem: string }> }) {
  const { city, problem } = await params;
  if (city !== 'lyon') notFound();
  const content = localProblems[problem];
  if (!content) notFound();
  const guide = content.guide ? guideBySlug[content.guide] : undefined;
  const faqJsonLd = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: content.faq.map(item => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
  return <main><Breadcrumbs items={[{ label: 'Plombier', href: '/professionnels' }, { label: 'Lyon', href: '/plombier/lyon' }, { label: content.title }]} /><section className="local-problem-hero"><PageHero eyebrow={`LYON · ${problem.replaceAll('-', ' ').toUpperCase()}`} title={content.title}><p>{content.intro}</p><ButtonLink href="/comment-ca-marche">Diagnostiquer gratuitement</ButtonLink></PageHero><div className="guide-photo"><Image src={content.image.src} alt={content.image.alt} fill sizes="(max-width: 850px) 100vw, 42vw" priority /></div></section><section className="section-v5"><SectionHeader eyebrow="CE QUE VOUS POUVEZ OBSERVER" title="Commencez par décrire le symptôme, pas par choisir une réparation."><ul>{content.observations.map(item => <li key={item}>{item}</li>)}</ul></SectionHeader><PhotoBand eyebrow="HYPOTHÈSES, PAS CERTITUDE" title="Une même apparence peut avoir plusieurs causes." text={content.causes.join(' · ')} image={content.image} light /></section><section className="section-v5"><SectionHeader eyebrow="VÉRIFICATIONS SÛRES" title="Une étape à la fois.">Effectuez uniquement les vérifications qui restent simples, accessibles et sans risque dans votre situation.</SectionHeader><ul className="local-check-list">{content.checks.map(item => <li key={item}>{item}</li>)}</ul></section><SafetyStop items={content.stop} /><section className="section-v5"><SectionHeader eyebrow="CONTINUER AVEC UN PROBLÈME PROCHE" title="Les situations qui se recoupent."/><div className="local-problems">{(localCrossLinks[problem] ?? []).map(link => <a key={link.href} href={link.href}>{link.label}<span>→</span></a>)}</div></section>{guide && <section className="section-v5"><SectionHeader eyebrow="GUIDE NALVIUM ASSOCIÉ" title="Approfondir une situation proche." /><ButtonLink href={`/guides/${guide.slug}`} secondary>Lire le guide « {guide.title} »</ButtonLink></section>}<section className="section-v5"><SectionHeader eyebrow="PASSER LA MAIN" title="Faire intervenir un professionnel peut être la bonne suite.">NALVIUM ne réalise aucun dépannage et ne présente ni artisan, ni tarif, ni délai inventé. Si l’origine reste incertaine, si le risque augmente ou si l’action dépasse une observation simple, arrêtez-vous.</SectionHeader><RelatedGuides slugs={content.related} /></section><section className="section-v5"><SectionHeader eyebrow="QUESTIONS FRÉQUENTES" title="Les réponses utiles avant d’agir." /><FAQ items={content.faq} /></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} /><SiteCta title="Montrez le problème à NALVIUM." /></main>;
}
